/**
 *
 * @file PWM_RegisterAddress.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 23 dic. 2021 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 23 dic. 2021     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_XHEADER_PWM_REGISTERADDRESS_H_
#define XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_XHEADER_PWM_REGISTERADDRESS_H_

#include <xDriver_MCU/PWM/Peripheral/xHeader/PWM_Enum.h>

#define PWM_GEN_REGISTER_NUM    ((UBase_t) 16UL)
#define PWM_GEN_EXT_REGISTER_NUM    ((UBase_t) 32UL)

#define PWM_BASE    ((UBase_t) 0x40028000UL)
#define PWM0_BASE    ((UBase_t) 0x40028000UL)

#define PWM_OFFSET    ((UBase_t) 0x00028000UL)
#define PWM0_OFFSET    ((UBase_t) 0x00028000UL)

#define PWM_BITBANDING_BASE    ((UBase_t) 0x42000000UL)

#define PWM_CTL_OFFSET    ((UBase_t) 0x0000UL)
#define PWM_SYNC_OFFSET    ((UBase_t) 0x0004UL)
#define PWM_OUTPUT_ENABLE_OFFSET    ((UBase_t) 0x0008UL)
#define PWM_OUTPUT_INVERT_OFFSET    ((UBase_t) 0x000CUL)
#define PWM_OUTPUT_FAULT_OFFSET    ((UBase_t) 0x0010UL)
#define PWM_INTEN_OFFSET    ((UBase_t) 0x0014UL)
#define PWM_RIS_OFFSET    ((UBase_t) 0x0018UL)
#define PWM_ISC_OFFSET    ((UBase_t) 0x001CUL)
#define PWM_STATUS_OFFSET    ((UBase_t) 0x0020UL)
#define PWM_OUTPUT_FAULTVAL_OFFSET    ((UBase_t) 0x0024UL)
#define PWM_OUTPUT_ENUPD_OFFSET    ((UBase_t) 0x0028UL)

#define PWM_GEN_CTL_OFFSET    ((UBase_t) 0x0000UL)
#define PWM_GEN_INTEN_OFFSET    ((UBase_t) 0x0004UL)
#define PWM_GEN_RIS_OFFSET    ((UBase_t) 0x0008UL)
#define PWM_GEN_ISC_OFFSET    ((UBase_t) 0x000CUL)
#define PWM_GEN_LOAD_OFFSET    ((UBase_t) 0x0010UL)
#define PWM_GEN_COUNT_OFFSET    ((UBase_t) 0x0014UL)
#define PWM_GEN_OUTA_CMP_OFFSET    ((UBase_t) 0x0018UL)
#define PWM_GEN_OUTB_CMP_OFFSET    ((UBase_t) 0x001CUL)
#define PWM_GEN_OUTA_ACTION_OFFSET    ((UBase_t) 0x0020UL)
#define PWM_GEN_OUTB_ACTION_OFFSET    ((UBase_t) 0x0024UL)
#define PWM_GEN_DB_CTL_OFFSET    ((UBase_t) 0x0028UL)
#define PWM_GEN_DB_RISE_OFFSET    ((UBase_t) 0x002CUL)
#define PWM_GEN_DB_FALL_OFFSET    ((UBase_t) 0x0030UL)
#define PWM_GEN_FAULT_PIN_ENABLE_OFFSET    ((UBase_t) 0x0034UL)
#define PWM_GEN_FAULT_DCMP_ENABLE_OFFSET    ((UBase_t) 0x0038UL)
#define PWM_GEN_FAULT_MIN_PERIOD_OFFSET    ((UBase_t) 0x003CUL)

#define PWM_GEN_REGISTER_BASE_OFFSET    ((UBase_t) 0x0040UL)
#define PWM_GEN_REGISTER_OFFSET    ((UBase_t) 0x0040UL)

#define PWM_GEN0_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_INTEN_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_INTEN_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_RIS_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_RIS_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_ISC_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_ISC_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_LOAD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_LOAD_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_COUNT_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_COUNT_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_OUTA_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_OUTA_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_OUTB_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_OUTB_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_OUTA_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_OUTA_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_OUTB_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_OUTB_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_DB_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_DB_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_DB_RISE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_DB_RISE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_DB_FALL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_DB_FALL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_FAULT_PIN_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_FAULT_PIN_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_FAULT_DCMP_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_FAULT_DCMP_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN0_FAULT_MIN_PERIOD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 0UL) + PWM_GEN_MINFLPER_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))

#define PWM_GEN1_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_INTEN_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_INTEN_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_RIS_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_RIS_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_ISC_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_ISC_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_LOAD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_LOAD_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_COUNT_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_COUNT_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_OUTA_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_OUTA_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_OUTB_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_OUTB_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_OUTA_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_OUTA_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_OUTB_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_OUTB_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_DB_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_DB_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_DB_RISE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_DB_RISE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_DB_FALL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_DB_FALL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_FAULT_PIN_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_FAULT_PIN_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_FAULT_DCMP_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_FAULT_DCMP_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN1_FAULT_MIN_PERIOD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 1UL) + PWM_GEN_MINFLPER_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))

#define PWM_GEN2_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_INTEN_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_INTEN_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_RIS_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_RIS_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_ISC_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_ISC_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_LOAD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_LOAD_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_COUNT_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_COUNT_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_OUTA_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_OUTA_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_OUTB_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_OUTB_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_OUTA_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_OUTA_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_OUTB_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_OUTB_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_DB_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_DB_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_DB_RISE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_DB_RISE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_DB_FALL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_DB_FALL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_FAULT_PIN_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_FAULT_PIN_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_FAULT_DCMP_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_FAULT_DCMP_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN2_FAULT_MIN_PERIOD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 2UL) + PWM_GEN_MINFLPER_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))

#define PWM_GEN3_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_INTEN_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_INTEN_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_RIS_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_RIS_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_ISC_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_ISC_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_LOAD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_LOAD_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_COUNT_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_COUNT_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_OUTA_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_OUTA_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_OUTB_CMP_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_OUTB_CMP_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_OUTA_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_OUTA_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_OUTB_ACTION_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_OUTB_ACTION_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_DB_CTL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_DB_CTL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_DB_RISE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_DB_RISE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_DB_FALL_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_DB_FALL_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_FAULT_PIN_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_FAULT_PIN_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_FAULT_DCMP_ENABLE_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_FAULT_DCMP_ENABLE_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))
#define PWM_GEN3_FAULT_MIN_PERIOD_OFFSET    ((UBase_t) ((PWM_GEN_REGISTER_OFFSET * 3UL) + PWM_GEN_MINFLPER_OFFSET + PWM_GEN_REGISTER_BASE_OFFSET))

#define PWM_GEN_EXT_FAULT_PIN_SENSE_OFFSET    ((UBase_t) 0x0000UL)
#define PWM_GEN_EXT_FAULT_PIN_STAT_OFFSET    ((UBase_t) 0x0004UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_OFFSET    ((UBase_t) 0x0008UL)

#define PWM_GEN_EXT_REGISTER_BASE_OFFSET    ((UBase_t) 0x0800UL)
#define PWM_GEN_EXT_REGISTER_OFFSET    ((UBase_t) 0x0080UL)

#define PWM_GEN0_EXT_FAULT_PIN_SENSE_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 0UL) + PWM_GEN_EXT_FAULT_PIN_SENSE_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN0_EXT_FAULT_PIN_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 0UL) + PWM_GEN_EXT_FAULT_PIN_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN0_EXT_FAULT_DCMP_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 0UL) + PWM_GEN_EXT_FAULT_DCMP_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))

#define PWM_GEN1_EXT_FAULT_PIN_SENSE_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 1UL) + PWM_GEN_EXT_FAULT_PIN_SENSE_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN1_EXT_FAULT_PIN_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 1UL) + PWM_GEN_EXT_FAULT_PIN_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN1_EXT_FAULT_DCMP_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 1UL) + PWM_GEN_EXT_FAULT_DCMP_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))

#define PWM_GEN2_EXT_FAULT_PIN_SENSE_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 2UL) + PWM_GEN_EXT_FAULT_PIN_SENSE_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN2_EXT_FAULT_PIN_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 2UL) + PWM_GEN_EXT_FAULT_PIN_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN2_EXT_FAULT_DCMP_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 2UL) + PWM_GEN_EXT_FAULT_DCMP_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))

#define PWM_GEN3_EXT_FAULT_PIN_SENSE_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 3UL) + PWM_GEN_EXT_FAULT_PIN_SENSE_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN3_EXT_FAULT_PIN_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 3UL) + PWM_GEN_EXT_FAULT_PIN_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))
#define PWM_GEN3_EXT_FAULT_DCMP_STAT_OFFSET    ((UBase_t) ((PWM_GEN_EXT_REGISTER_OFFSET * 3UL) + PWM_GEN_EXT_FAULT_DCMP_STAT_OFFSET + PWM_GEN_EXT_REGISTER_BASE_OFFSET))

#define PWM_PP_OFFSET    ((UBase_t) 0x0FC0UL)
#define PWM_CC_OFFSET    ((UBase_t) 0x0FC8UL)

#endif /* XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_XHEADER_PWM_REGISTERADDRESS_H_ */
