/**
 *
 * @file PWM_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim May 26, 2021 @endverbatim
 *
 * @author
 * @verbatim indevicemex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * May 26, 2021        indevicemex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_PWM_PERIPHERAL_XHEADER_PWM_ENUM_H_
#define XDRIVER_MCU_PWM_PERIPHERAL_XHEADER_PWM_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Enum.h>

typedef enum
{
    PWM_enERROR_OK = (uint32_t) MCU_enERROR_OK,
    PWM_enERROR_POINTER = (uint32_t) MCU_enERROR_POINTER,
    PWM_enERROR_VALUE = (uint32_t) MCU_enERROR_VALUE,
    PWM_enERROR_RANGE = (uint32_t) MCU_enERROR_RANGE,
    PWM_enERROR_EMPTY = (uint32_t) MCU_enERROR_EMPTY,
    PWM_enERROR_TIMEOUT = (uint32_t) MCU_enERROR_TIMEOUT,
    PWM_enERROR_UNDEF = (uint32_t) MCU_enERROR_UNDEF,
}PWM_nERROR;

typedef enum
{
    PWM_enSTATE_DIS = (uint32_t) MCU_enSTATE_DIS,
    PWM_enSTATE_ENA = (uint32_t) MCU_enSTATE_ENA,
    PWM_enSTATE_UNDEF = (uint32_t) MCU_enSTATE_UNDEF,
} PWM_nSTATE;

typedef enum
{
    PWM_enSTATUS_INACTIVE = (uint32_t) MCU_enSTATUS_INACTIVE,
    PWM_enSTATUS_ACTIVE = (uint32_t) MCU_enSTATUS_ACTIVE,
    PWM_enSTATUS_UNDEF = (uint32_t) MCU_enSTATUS_UNDEF,
} PWM_nSTATUS;

typedef enum
{
    PWM_enPRI0 = (uint32_t) MCU_enPRI0,
    PWM_enPRI1 = (uint32_t) MCU_enPRI1,
    PWM_enPRI2 = (uint32_t) MCU_enPRI2,
    PWM_enPRI3 = (uint32_t) MCU_enPRI3,
    PWM_enPRI4 = (uint32_t) MCU_enPRI4,
    PWM_enPRI5 = (uint32_t) MCU_enPRI5,
    PWM_enPRI6 = (uint32_t) MCU_enPRI6,
    PWM_enPRI7 = (uint32_t) MCU_enPRI7,
    PWM_enPRIMAX = (uint32_t) MCU_enPRIMAX,
    PWM_enDEFAULT = (uint32_t) MCU_enDEFAULT,
}PWM_nPRIORITY;

typedef enum
{
    PWM_enMODULE_0 = 0UL,
    PWM_enMODULE_MAX = 1UL,
}PWM_nMODULE;

typedef enum
{
    PWM_enGEN_0 = 0UL,
    PWM_enGEN_1 = 1UL,
    PWM_enGEN_2 = 2UL,
    PWM_enGEN_3 = 3UL,
    PWM_enGEN_MAX = 4UL,
    PWM_enGEN_UNDEF = 0x7FFFFFFFUL,
}PWM_nGENERATOR;

typedef enum
{
    PWM_enGENMASK_NONE = 0x0UL,
    PWM_enGENMASK_0 = 0x1UL,
    PWM_enGENMASK_1 = 0x2UL,
    PWM_enGENMASK_2 = 0x4UL,
    PWM_enGENMASK_3 = 0x8UL,
    PWM_enGENMASK_ALL = 0xFUL,
    PWM_enGENMASK_MAX = 0x10UL,
    PWM_enGENMASK_UNDEF = 0x7FFFFFFFUL,
}PWM_nGENMASK;

typedef enum
{
    PWM_enFAULT_0 = 0UL,
    PWM_enFAULT_1 = 1UL,
    PWM_enFAULT_2 = 2UL,
    PWM_enFAULT_3 = 3UL,
    PWM_enFAULT_MAX = 4UL,
    PWM_enFAULT_UNDEF = 0x7FFFFFFFUL,
}PWM_nFAULT;

typedef enum
{
    PWM_enFAULTMASK_NONE = 0x0UL,
    PWM_enFAULTMASK_0 = 0x1UL,
    PWM_enFAULTMASK_1 = 0x2UL,
    PWM_enFAULTMASK_2 = 0x4UL,
    PWM_enFAULTMASK_3 = 0x8UL,
    PWM_enFAULTMASK_ALL = 0xFUL,
    PWM_enFAULTMASK_MAX = 0x10UL,
    PWM_enFAULTMASK_UNDEF = 0x7FFFFFFFUL,
}PWM_nFAULTMASK;

/**
 * PWM Gen interrupts
 */
typedef enum
{
    PWM_enGEN_INT_SW = 0UL,
    PWM_enGEN_INT_ZERO = 1UL,
    PWM_enGEN_INT_LOAD = 2UL,
    PWM_enGEN_INT_CMPA_UP = 3UL,
    PWM_enGEN_INT_CMPA_DOWN = 4UL,
    PWM_enGEN_INT_CMPB_UP = 5UL,
    PWM_enGEN_INT_CMPB_DOWN = 6UL,
    PWM_enGEN_INT_MAX = 7UL,
}PWM_nGEN_INT;

typedef enum
{
    PWM_enGEN_INTMASK_NONE = 0x0UL,
    PWM_enGEN_INTMASK_ZERO = 0x1UL,
    PWM_enGEN_INTMASK_LOAD = 0x2UL,
    PWM_enGEN_INTMASK_CMPA_UP = 0x4UL,
    PWM_enGEN_INTMASK_CMPA_DOWN = 0x8UL,
    PWM_enGEN_INTMASK_CMPB_UP = 0x10UL,
    PWM_enGEN_INTMASK_CMPB_DOWN = 0x20UL,
    PWM_enGEN_INTMASK_ALL = 0x3FUL,
    PWM_enGEN_INTMASK_MAX = 0x40UL,
}PWM_nGEN_INTMASK;


/**
 * PWM Gen interrupts
 */
typedef enum
{
    PWM_enFAULT_INT_SW = 0UL,
    PWM_enFAULT_INT_FAULT = 1UL,
    PWM_enFAULT_INT_GEN1_FAULT = 2UL,
    PWM_enFAULT_INT_GEN2_FAULT = 3UL,
    PWM_enFAULT_INT_GEN3_FAULT = 4UL,
    PWM_enFAULT_INT_DCMP0 = 5UL,
    PWM_enFAULT_INT_DCMP1 = 6UL,
    PWM_enFAULT_INT_DCMP2 = 7UL,
    PWM_enFAULT_INT_DCMP3 = 8UL,
    PWM_enFAULT_INT_DCMP4 = 9UL,
    PWM_enFAULT_INT_DCMP5 = 10UL,
    PWM_enFAULT_INT_DCMP6 = 11UL,
    PWM_enFAULT_INT_DCMP7 = 12UL,
    PWM_enFAULT_INT_MAX = 13UL,
}PWM_nFAULT_INT;

typedef enum
{
    PWM_enFAULT_INTMASK_NONE = 0x0UL,
    PWM_enFAULT_INTMASK_FAULT = 0x1UL,
    PWM_enFAULT_INTMASK_ALL = 0x1UL,
    PWM_enFAULT_INTMASK_MAX = 0x2UL,
}PWM_nFAULT_INTMASK;

typedef enum
{
    PWM_enDEADBAND_UPDATE_IMMEDIATE = 0x0UL,
    PWM_enDEADBAND_UPDATE_LOCAL = 0x2UL,
    PWM_enDEADBAND_UPDATE_GLOBAL = 0x3UL,
    PWM_enDEADBAND_UPDATE_UNDEF = 0x7FFFFFFFUL,
}PWM_nDEADBAND_UPDATE;

typedef enum
{
    PWM_enFAULT_INPUT_NONE = 0x0UL,
    PWM_enFAULT_INPUT_0 = 0x1UL,
    PWM_enFAULT_INPUT_1 = 0x2UL,
    PWM_enFAULT_INPUT_2 = 0x4UL,
    PWM_enFAULT_INPUT_3 = 0x8UL,
    PWM_enFAULT_INPUT_ALL = 0xFUL,
    PWM_enFAULT_INPUT_MAX = 0x10UL,
    PWM_enFAULT_INPUT_UNDEF = 0x7FFFFFFFUL,
}PWM_nFAULT_INPUT;

typedef enum
{
    PWM_enLEVEL_HIGH = 0x0UL,
    PWM_enLEVEL_LOW = 0x1UL,
    PWM_enLEVEL_UNDEF = 0x7FFFFFFFUL,
}PWM_nLEVEL;

typedef enum
{
    PWM_enFAULT_DCOMP_NONE = 0x0UL,
    PWM_enFAULT_DCOMP_0 = 0x1UL,
    PWM_enFAULT_DCOMP_1 = 0x2UL,
    PWM_enFAULT_DCOMP_2 = 0x4UL,
    PWM_enFAULT_DCOMP_3 = 0x8UL,
    PWM_enFAULT_DCOMP_4 = 0x10UL,
    PWM_enFAULT_DCOMP_5 = 0x20UL,
    PWM_enFAULT_DCOMP_6 = 0x40UL,
    PWM_enFAULT_DCOMP_7 = 0x80UL,
    PWM_enFAULT_DCOMP_ALL = 0xFFUL,
    PWM_enFAULT_DCOMP_MAX = 0x100UL,
    PWM_enFAULT_DCOMP_UNDEF = 0x7FFFFFFFUL,
}PWM_nFAULT_DCOMP;

typedef enum
{
    PWM_enGENERATOR_UPDATE_IMMEDIATE = 0x0UL,
    PWM_enGENERATOR_UPDATE_LOCAL = 0x2UL,
    PWM_enGENERATOR_UPDATE_GLOBAL = 0x3UL,
    PWM_enGENERATOR_UPDATE_UNDEF = 0x7FFFFFFFUL,
}PWM_nGENERATOR_UPDATE;


typedef enum
{
    PWM_enOUTPUT_NUMBER_NONE = 0x0UL,
    PWM_enOUTPUT_NUMBER_GEN0A = 0x1UL,
    PWM_enOUTPUT_NUMBER_GEN0B = 0x2UL,
    PWM_enOUTPUT_NUMBER_GEN1A = 0x4UL,
    PWM_enOUTPUT_NUMBER_GEN1B = 0x8UL,
    PWM_enOUTPUT_NUMBER_GEN2A = 0x10UL,
    PWM_enOUTPUT_NUMBER_GEN2B = 0x20UL,
    PWM_enOUTPUT_NUMBER_GEN3A = 0x40UL,
    PWM_enOUTPUT_NUMBER_GEN3B = 0x80UL,
    PWM_enOUTPUT_NUMBER_ALL = 0xFFUL,
    PWM_enOUTPUT_NUMBER_MAX = 0x100UL,
    PWM_enOUTPUT_NUMBER_UNDEF = 0x7FFFFFFFUL,
}PWM_nOUTPUT_NUMBER;

typedef enum
{
    PWM_enOUTPUT_NONE = 0x0UL,
    PWM_enOUTPUT_A = 0x1UL,
    PWM_enOUTPUT_B = 0x2UL,
    PWM_enOUTPUT_BOTH = 0x3UL,
    PWM_enOUTPUT_MAX = 0x4UL,
    PWM_enOUTPUT_UNDEF = 0x7FFFFFFFUL,
}PWM_nOUTPUT;

typedef enum
{
    PWM_enOUTPUT_UPDATE_IMMEDIATE = 0x0UL,
    PWM_enOUTPUT_UPDATE_LOCAL = 0x2UL,
    PWM_enOUTPUT_UPDATE_GLOBAL = 0x3UL,
    PWM_enOUTPUT_UPDATE_MAX = 0x4UL,
    PWM_enOUTPUT_UPDATE_UNDEF = 0x7FFFFFFFUL,
}PWM_nOUTPUT_UPDATE;

typedef enum
{
    PWM_enOUTPUT_FAULT_LOW = 0x0UL,
    PWM_enOUTPUT_FAULT_HIGH = 0x1UL,
    PWM_enOUTPUT_FAULT_UNDEF = 0x7FFFFFFFUL,
}PWM_nOUTPUT_FAULT;

typedef enum
{
    PWM_enACTION_NOTHING = 0x0UL,
    PWM_enACTION_INVERT = 0x1UL,
    PWM_enACTION_LOW = 0x2UL,
    PWM_enACTION_HIGH = 0x3UL,
    PWM_enACTION_UNDEF = 0x7FFFFFFFUL,
}PWM_nACTION;

typedef enum
{
    PWM_enEVENT_ZERO = 0x0UL,
    PWM_enEVENT_LOAD = 0x1UL,
    PWM_enEVENT_COMPA_UP = 0x2UL,
    PWM_enEVENT_COMPA_DOWN = 0x3UL,
    PWM_enEVENT_COMPB_UP = 0x4UL,
    PWM_enEVENT_COMPB_DOWN = 0x5UL,
    PWM_enEVENT_UNDEF = 0x7FFFFFFFUL,
}PWM_nEVENT;

typedef enum
{
    PWM_enDIRECTION_DOWN = 0x0UL,
    PWM_enDIRECTION_UP_DOWN = 0x1UL,
    PWM_enDIRECTION_UNDEF = 0x7FFFFFFFUL,
}PWM_nDIRECTION;


typedef enum
{
    PWM_enSTALL_FREEZE = 0UL,
    PWM_enSTALL_CONTINUE = 1UL,
    PWM_enSTALL_UNDEF = 0x7FFFFFFFUL,
}PWM_nSTALL;

typedef enum
{
    PWM_enCLOCK_SYSCLK = 0x0UL,
    PWM_enCLOCK_DIVIDER = 0x1UL,
    PWM_enCLOCK_UNDEF = 0x7FFFFFFFUL,
}PWM_nCLOCK;

typedef enum
{
    PWM_enCLOCK_DIV_2 = 0x0UL,
    PWM_enCLOCK_DIV_4 = 0x1UL,
    PWM_enCLOCK_DIV_8 = 0x2UL,
    PWM_enCLOCK_DIV_16 = 0x3UL,
    PWM_enCLOCK_DIV_32 = 0x4UL,
    PWM_enCLOCK_DIV_64 = 0x5UL,
    PWM_enCLOCK_DIV_MAX = 0x5UL,
    PWM_enCLOCK_DIV_UNDEF = 0x7FFFFFFFUL,
}PWM_nCLOCK_DIV;

typedef enum
{
    PWM_enCLOCK_DIV_NUM_2 = 0x2UL,
    PWM_enCLOCK_DIV_NUM_4 = 0x4UL,
    PWM_enCLOCK_DIV_NUM_8 = 0x8UL,
    PWM_enCLOCK_DIV_NUM_16 = 16UL,
    PWM_enCLOCK_DIV_NUM_32 = 32UL,
    PWM_enCLOCK_DIV_NUM_64 = 64UL,
    PWM_enCLOCK_DIV_NUM_MASK = 0x7FUL,
    PWM_enCLOCK_DIV_NUM_UNDEF = 0x7FFFFFFFUL,
}PWM_nCLOCK_DIV_NUM;

typedef MCU_Register_t PWM_Register_t;
typedef MCU_pvfIRQVectorHandler_t PWM_pvfIRQVectorHandler_t;
typedef MCU_pvfIRQSourceHandler_t PWM_pvfIRQSourceHandler_t;

#endif /* XDRIVER_MCU_PWM_PERIPHERAL_XHEADER_PWM_ENUM_H_ */
