/**
 *
 * @file SCB_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 19 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 19 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Variables.h>

#define SCB_VECTOR_TABLE_SIZE ((uint32_t) 0x00000100UL)

typedef enum
{
    SCB_enOK = 0UL,
    SCB_enERROR = 1UL,
}SCB_nSTATUS;

typedef enum
{
    SCB_enPRIGROUP_XXX = 0UL,
    SCB_enPRIGROUP_XXY = 1UL,
    SCB_enPRIGROUP_XYY = 2UL,
    SCB_enPRIGROUP_YYY = 3UL,
    SCB_enPRIGROUP_MAX = 4UL,
    SCB_enPRIGROUP_ERROR = 0xFFFFFFFFUL,
}SCB_nPRIGROUP;

typedef enum
{
    SCB_enNOPENDING = 0UL,
    SCB_enPENDING = 1UL,
}SCB_nPENDSTATE;

typedef enum
{
    SCB_enUCFSR_UNDEFINSTR = 0x0001UL,
    SCB_enUCFSR_INVSTATE = 0x0002UL,
    SCB_enUCFSR_INVPC = 0x0004UL,
    SCB_enUCFSR_NOCP = 0x0008UL,
    SCB_enUCFSR_UNALIGNED = 0x0100UL,
    SCB_enUCFSR_DIVBYZERO = 0x0200UL,
}SCB_nUCFSR;

typedef enum
{
    SCB_enBCFSR_IBUSERR = 0x01UL,
    SCB_enBCFSR_PRECISERR = 0x02UL,
    SCB_enBCFSR_IMPRECISERR = 0x04UL,
    SCB_enBCFSR_UNSTKERR = 0x08UL,
    SCB_enBCFSR_STKERR = 0x10UL,
    SCB_enBCFSR_LSPERR = 0x20UL,
    SCB_enBCFSR_BFARVALID = 0x80UL,
}SCB_nBCFSR;

typedef enum
{
    SCB_enMCFSR_IACCVIOL = 0x01UL,
    SCB_enMCFSR_DACCVIOL = 0x02UL,
    SCB_enMCFSR_MUNSTKERR = 0x08UL,
    SCB_enMCFSR_MSTKERR = 0x10UL,
    SCB_enMCFSR_MLSPERR = 0x20UL,
    SCB_enMCFSR_MMARVALID = 0x80UL,
}SCB_nMCFSR;

typedef enum
{
    SCB_enSHPR0 = 0UL,
    SCB_enSHPR1 = 1UL,
    SCB_enSHPR2 = 2UL,
    SCB_enSHPR3 = 3UL,
    SCB_enSHPR4 = 4UL,
    SCB_enSHPR5 = 5UL,
    SCB_enSHPR6 = 6UL,
    SCB_enSHPR7 = 7UL,
}SCB_nSHPR;

typedef enum
{
    SCB_enALIGN_4BYTE = 0UL,
    SCB_enALIGN_8BYTE = 1UL,
    SCB_enALIGN_ERROR = 0xFFFFFFFFUL,
}SCB_nAlignment;

typedef enum
{
    SCB_enWAKEUP_ONLY = 0UL,
    SCB_enWAKEUP_ALL = 1UL,
    SCB_enWAKEUP_ERROR = 0xFFFFFFFFUL,
}SCB_nWAKEUPSOURCE;

typedef enum
{
    SCB_enSLEEPONEXIT_NOSLEEP = 0UL,
    SCB_enSLEEPONEXIT_SLEEP = 1UL,
    SCB_enSLEEPONEXIT_ERROR = 0xFFFFFFFFUL,
}SCB_nSLEEPONEXIT;

typedef enum
{
    SCB_enSleepDeep_Sleep = 0UL,
    SCB_enSleepDeep_DeepSleep = 1UL,
    SCB_enSleepDeep_ERROR = 0xFFFFFFFFUL,
}SCB_nSleepDeep;

typedef enum
{
    SCB_enVECISR_THREAD = 0UL,
    SCB_enVECISR_RESET = 1UL,
    SCB_enVECISR_NMI = 2UL,
    SCB_enVECISR_HARDFAULT = 3UL,
    SCB_enVECISR_MEMMANAGE = 4UL,
    SCB_enVECISR_BUSFAULT = 5UL,
    SCB_enVECISR_USAGEFAULT = 6UL,
    SCB_enVECISR_RES7 = 7UL,
    SCB_enVECISR_RES8 = 8UL,
    SCB_enVECISR_RES9 = 9UL,
    SCB_enVECISR_RES10 = 10UL,
    SCB_enVECISR_SVCALL = 11UL,
    SCB_enVECISR_DEBUGMON = 12UL,
    SCB_enVECISR_RES13 = 13UL,
    SCB_enVECISR_PENDSV = 14UL,
    SCB_enVECISR_SYSTICK = 15UL,
    SCB_enVECISR_GPIOA = 0UL + 16UL,
    SCB_enVECISR_GPIOB = 1UL + 16UL,
    SCB_enVECISR_GPIOC = 2UL + 16UL,
    SCB_enVECISR_GPIOD = 3UL + 16UL,
    SCB_enVECISR_GPIOE = 4UL + 16UL,
    SCB_enVECISR_UART0 = 5UL + 16UL,
    SCB_enVECISR_UART1 = 6UL + 16UL,
    SCB_enVECISR_SSI0 = 7UL + 16UL,
    SCB_enVECISR_I2C0 = 8UL + 16UL,
    SCB_enVECISR_PWM0FAULT = 9UL + 16UL,
    SCB_enVECISR_PWM0GEN0 = 10UL + 16UL,
    SCB_enVECISR_PWM0GEN1 = 11UL + 16UL,
    SCB_enVECISR_PWM0GEN2 = 12UL + 16UL,
    SCB_enVECISR_QEI0 = 13UL + 16UL,
    SCB_enVECISR_ADC0SEQ0 = 14UL + 16UL,
    SCB_enVECISR_ADC0SEQ1 = 15UL + 16UL,
    SCB_enVECISR_ADC0SEQ2 = 16UL + 16UL,
    SCB_enVECISR_ADC0SEQ3 = 17UL + 16UL,
    SCB_enVECISR_WDT01 = 18UL + 16UL,
    SCB_enVECISR_TIMER0A = 19UL + 16UL,
    SCB_enVECISR_TIMER0B = 20UL + 16UL,
    SCB_enVECISR_TIMER1A = 21UL + 16UL,
    SCB_enVECISR_TIMER1B = 22UL + 16UL,
    SCB_enVECISR_TIMER2A = 23UL + 16UL,
    SCB_enVECISR_TIMER2B = 24UL + 16UL,
    SCB_enVECISR_ACMP0 = 25UL + 16UL,
    SCB_enVECISR_ACMP1 = 26UL + 16UL,
    SCB_enVECISR_ACMP2 = 27UL + 16UL,
    SCB_enVECISR_SYSCTL = 28UL + 16UL,
    SCB_enVECISR_FLASH = 29UL + 16UL,
    SCB_enVECISR_GPIOF = 30UL + 16UL,
    SCB_enVECISR_GPIOG = 31UL + 16UL,
    SCB_enVECISR_GPIOH = 32UL + 16UL,
    SCB_enVECISR_UART2 = 33UL + 16UL,
    SCB_enVECISR_SSI1 = 34UL + 16UL,
    SCB_enVECISR_TIMER3A = 35UL + 16UL,
    SCB_enVECISR_TIMER3B = 36UL + 16UL,
    SCB_enVECISR_I2C1 = 37UL + 16UL,
    SCB_enVECISR_CAN0 = 38UL + 16UL,
    SCB_enVECISR_CAN1 = 39UL + 16UL,
    SCB_enVECISR_ETH = 40UL + 16UL,
    SCB_enVECISR_HIB = 41UL + 16UL,
    SCB_enVECISR_USB = 42UL + 16UL,
    SCB_enVECISR_PWM0GEN3 = 43UL + 16UL,
    SCB_enVECISR_UDMASOFT = 44UL + 16UL,
    SCB_enVECISR_UDMAERROR = 45UL + 16UL,
    SCB_enVECISR_ADC1SEQ0 = 46UL + 16UL,
    SCB_enVECISR_ADC1SEQ1 = 47UL + 16UL,
    SCB_enVECISR_ADC1SEQ2 = 48UL + 16UL,
    SCB_enVECISR_ADC1SEQ3 = 49UL + 16UL,
    SCB_enVECISR_EPI0 = 50UL + 16UL,
    SCB_enVECISR_GPIOJ = 51UL + 16UL,
    SCB_enVECISR_GPIOK = 52UL + 16UL,
    SCB_enVECISR_GPIOL = 53UL + 16UL,
    SCB_enVECISR_SSI2 = 54UL + 16UL,
    SCB_enVECISR_SSI3 = 55UL + 16UL,
    SCB_enVECISR_UART3 = 56UL + 16UL,
    SCB_enVECISR_UART4 = 57UL + 16UL,
    SCB_enVECISR_UART5 = 58UL + 16UL,
    SCB_enVECISR_UART6 = 59UL + 16UL,
    SCB_enVECISR_UART7 = 60UL + 16UL,
    SCB_enVECISR_I2C2 = 61UL + 16UL,
    SCB_enVECISR_I2C3 = 62UL + 16UL,
    SCB_enVECISR_TIMER4A = 63UL + 16UL,
    SCB_enVECISR_TIMER4B = 64UL + 16UL,
    SCB_enVECISR_TIMER5A = 65UL + 16UL,
    SCB_enVECISR_TIMER5B = 66UL + 16UL,
    SCB_enVECISR_SYSEXC = 67UL + 16UL,
    SCB_enVECISR_RES84 = 68UL + 16UL,
    SCB_enVECISR_RES85 = 69UL + 16UL,
    SCB_enVECISR_I2C4 = 70UL + 16UL,
    SCB_enVECISR_I2C5 = 71UL + 16UL,
    SCB_enVECISR_GPIOM = 72UL + 16UL,
    SCB_enVECISR_GPION = 73UL + 16UL,
    SCB_enVECISR_RES90 = 74UL + 16UL,
    SCB_enVECISR_TAMPER = 75UL + 16UL,
    SCB_enVECISR_GPIOP = 76UL + 16UL,
    SCB_enVECISR_GPIOP1 = 77UL + 16UL,
    SCB_enVECISR_GPIOP2 = 78UL + 16UL,
    SCB_enVECISR_GPIOP3 = 79UL + 16UL,
    SCB_enVECISR_GPIOP4 = 80UL + 16UL,
    SCB_enVECISR_GPIOP5 = 81UL + 16UL,
    SCB_enVECISR_GPIOP6 = 82UL + 16UL,
    SCB_enVECISR_GPIOP7 = 83UL + 16UL,
    SCB_enVECISR_GPIOQ = 84UL + 16UL,
    SCB_enVECISR_GPIOQ1 = 85UL + 16UL,
    SCB_enVECISR_GPIOQ2 = 86UL + 16UL,
    SCB_enVECISR_GPIOQ3 = 87UL + 16UL,
    SCB_enVECISR_GPIOQ4 = 88UL + 16UL,
    SCB_enVECISR_GPIOQ5 = 89UL + 16UL,
    SCB_enVECISR_GPIOQ6 = 90UL + 16UL,
    SCB_enVECISR_GPIOQ7 = 91UL + 16UL,
    SCB_enVECISR_GPIOR = 92UL + 16UL,
    SCB_enVECISR_GPIOS = 93UL + 16UL,
    SCB_enVECISR_SHA_MD5 = 94UL + 16UL,
    SCB_enVECISR_AES = 95UL + 16UL,
    SCB_enVECISR_DES = 96UL + 16UL,
    SCB_enVECISR_LCD = 97UL + 16UL,
    SCB_enVECISR_TIMER6A = 98UL + 16UL,
    SCB_enVECISR_TIMER6B = 99UL + 16UL,
    SCB_enVECISR_TIMER7A = 100UL + 16UL,
    SCB_enVECISR_TIMER7B = 101UL + 16UL,
    SCB_enVECISR_I2C6 = 102UL + 16UL,
    SCB_enVECISR_I2C7 = 103UL + 16UL,
    SCB_enVECISR_KEYBOARD = 104UL + 16UL,
    SCB_enVECISR_ONEWIRE = 105UL + 16UL,
    SCB_enVECISR_PS2 = 106UL + 16UL,
    SCB_enVECISR_LEDSEQ = 107UL + 16UL,
    SCB_enVECISR_IR = 108UL + 16UL,
    SCB_enVECISR_I2C8 = 109UL + 16UL,
    SCB_enVECISR_I2C9 = 110UL + 16UL,
    SCB_enVECISR_GPIOT = 111UL + 16UL,
    SCB_enVECISR_FAN = 112UL + 16UL,
    SCB_enVECISR_RES129 = 113UL + 16UL,
}SCB_nVECISR;

#endif /* XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_ */
