/*
 * SYSCTL_MainOsc.h
 *
 *  Created on: 13 jun. 2021
 *      Author: InDeviceMex
 */

#ifndef XDRIVER_MCU_SYSCTL_DRIVER_XHEADER_SYSCTL_MAINOSC_H_
#define XDRIVER_MCU_SYSCTL_DRIVER_XHEADER_SYSCTL_MAINOSC_H_

#include <xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h>

SYSCTL_nERROR SYSCTL__enSetMOSCMonitorState(SYSCTL_nMODULE enModuleArg, SYSCTL_nSTATE enStateArg);
SYSCTL_nERROR SYSCTL__enGetMOSCMonitorState(SYSCTL_nMODULE enModuleArg, SYSCTL_nSTATE* penStateArg);

SYSCTL_nERROR SYSCTL__enSetMOSCFailureAction(SYSCTL_nMODULE enModuleArg, SYSCTL_nMOSC_FAILURE enActionArg);
SYSCTL_nERROR SYSCTL__enGetMOSCFailureAction(SYSCTL_nMODULE enModuleArg, SYSCTL_nMOSC_FAILURE* penActionArg);

SYSCTL_nERROR SYSCTL__enSetMOSCState(SYSCTL_nMODULE enModuleArg, SYSCTL_nSTATE enStateArg);
SYSCTL_nERROR SYSCTL__enGetMOSCState(SYSCTL_nMODULE enModuleArg, SYSCTL_nSTATE* penStateArg);

SYSCTL_nERROR SYSCTL__enSetMOSCPowerState(SYSCTL_nMODULE enModuleArg, SYSCTL_nSTATE enStateArg);
SYSCTL_nERROR SYSCTL__enGetMOSCPowerState(SYSCTL_nMODULE enModuleArg, SYSCTL_nSTATE* penStateArg);

SYSCTL_nERROR SYSCTL__enSetMOSCFrequencyRange(SYSCTL_nMODULE enModuleArg, SYSCTL_nMOSC_RANGE enRangeArg);
SYSCTL_nERROR SYSCTL__enGetMOSCFrequencyRange(SYSCTL_nMODULE enModuleArg, SYSCTL_nMOSC_RANGE* penRangeArg);

#endif /* XDRIVER_MCU_SYSCTL_DRIVER_XHEADER_SYSCTL_MAINOSC_H_ */
