/*
 * SYSCTL_ResetBehavior.h
 *
 *  Created on: 13 jun. 2021
 *      Author: InDeviceMex
 */

#ifndef XDRIVER_MCU_SYSCTL_DRIVER_XHEADER_SYSCTL_RESETBEHAVIOR_H_
#define XDRIVER_MCU_SYSCTL_DRIVER_XHEADER_SYSCTL_RESETBEHAVIOR_H_

#include <xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h>

SYSCTL_nERROR SYSCTL__enSetResetBehavior_External(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR enBehaviorArg);
SYSCTL_nERROR SYSCTL__enGetResetBehavior_External(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR* penBehaviorArg);

SYSCTL_nERROR SYSCTL__enSetResetBehavior_BOR(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR enBehaviorArg);
SYSCTL_nERROR SYSCTL__enGetResetBehavior_BOR(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR* penBehaviorArg);

SYSCTL_nERROR SYSCTL__enSetResetBehavior_WDG0(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR enBehaviorArg);
SYSCTL_nERROR SYSCTL__enGetResetBehavior_WDG0(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR* penBehaviorArg);

SYSCTL_nERROR SYSCTL__enSetResetBehavior_WDG1(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR enBehaviorArg);
SYSCTL_nERROR SYSCTL__enGetResetBehavior_WDG1(SYSCTL_nMODULE enModuleArg, SYSCTL_nRESET_BEHAVIOR* penBehaviorArg);

#endif /* XDRIVER_MCU_SYSCTL_DRIVER_XHEADER_SYSCTL_RESETBEHAVIOR_H_ */
