/**
 *
 * @file NVIC_RegisterDefines_STIR.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 22 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_STIR_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_STIR_H_

#include <xDriver_MCU/Common/xHeader/MCU_Variables.h>

/********************************************************************************************/
/************************************* STIR ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_STIR_R_INTID_MASK    ((uint32_t) 0x000000FFUL)
#define NVIC_STIR_R_INTID_BIT    ((uint32_t) 0UL)
#define NVIC_STIR_R_INTID_GPIOA    ((uint32_t) 0UL)
#define NVIC_STIR_R_INTID_GPIOB    ((uint32_t) 1UL)
#define NVIC_STIR_R_INTID_GPIOC    ((uint32_t) 2UL)
#define NVIC_STIR_R_INTID_GPIOD    ((uint32_t) 3UL)
#define NVIC_STIR_R_INTID_GPIOE    ((uint32_t) 4UL)
#define NVIC_STIR_R_INTID_UART0    ((uint32_t) 5UL)
#define NVIC_STIR_R_INTID_UART1    ((uint32_t) 6UL)
#define NVIC_STIR_R_INTID_SSI0    ((uint32_t) 7UL)
#define NVIC_STIR_R_INTID_I2C0    ((uint32_t) 8UL)
#define NVIC_STIR_R_INTID_PWM0FAULT    ((uint32_t) 9UL)
#define NVIC_STIR_R_INTID_PWM0GEN0    ((uint32_t) 10UL)
#define NVIC_STIR_R_INTID_PWM0GEN1    ((uint32_t) 11UL)
#define NVIC_STIR_R_INTID_PWM0GEN2    ((uint32_t) 12UL)
#define NVIC_STIR_R_INTID_QEI0    ((uint32_t) 13UL)
#define NVIC_STIR_R_INTID_ADC0SEQ0    ((uint32_t) 14UL)
#define NVIC_STIR_R_INTID_ADC0SEQ1    ((uint32_t) 15UL)
#define NVIC_STIR_R_INTID_ADC0SEQ2    ((uint32_t) 16UL)
#define NVIC_STIR_R_INTID_ADC0SEQ3    ((uint32_t) 17UL)
#define NVIC_STIR_R_INTID_WDT01    ((uint32_t) 18UL)
#define NVIC_STIR_R_INTID_TIMER0A    ((uint32_t) 19UL)
#define NVIC_STIR_R_INTID_TIMER0B    ((uint32_t) 20UL)
#define NVIC_STIR_R_INTID_TIMER1A    ((uint32_t) 21UL)
#define NVIC_STIR_R_INTID_TIMER1B    ((uint32_t) 22UL)
#define NVIC_STIR_R_INTID_TIMER2A    ((uint32_t) 23UL)
#define NVIC_STIR_R_INTID_TIMER2B    ((uint32_t) 24UL)
#define NVIC_STIR_R_INTID_ACMP0    ((uint32_t) 25UL)
#define NVIC_STIR_R_INTID_ACMP1    ((uint32_t) 26UL)
#define NVIC_STIR_R_INTID_ACMP2    ((uint32_t) 27UL)
#define NVIC_STIR_R_INTID_SYSCTL    ((uint32_t) 28UL)
#define NVIC_STIR_R_INTID_FLASH    ((uint32_t) 29UL)
#define NVIC_STIR_R_INTID_GPIOF    ((uint32_t) 30UL)
#define NVIC_STIR_R_INTID_GPIOG    ((uint32_t) 31UL)
#define NVIC_STIR_R_INTID_GPIOH    ((uint32_t) 32UL)
#define NVIC_STIR_R_INTID_UART2    ((uint32_t) 33UL)
#define NVIC_STIR_R_INTID_SSI1    ((uint32_t) 34UL)
#define NVIC_STIR_R_INTID_TIMER3A    ((uint32_t) 35UL)
#define NVIC_STIR_R_INTID_TIMER3B    ((uint32_t) 36UL)
#define NVIC_STIR_R_INTID_I2C1    ((uint32_t) 37UL)
#define NVIC_STIR_R_INTID_CAN0    ((uint32_t) 38UL)
#define NVIC_STIR_R_INTID_CAN1    ((uint32_t) 39UL)
#define NVIC_STIR_R_INTID_ETH    ((uint32_t) 40UL)
#define NVIC_STIR_R_INTID_HIB    ((uint32_t) 41UL)
#define NVIC_STIR_R_INTID_USB    ((uint32_t) 42UL)
#define NVIC_STIR_R_INTID_PWM0GEN3    ((uint32_t) 43UL)
#define NVIC_STIR_R_INTID_UDMASOFT    ((uint32_t) 44UL)
#define NVIC_STIR_R_INTID_UDMAERROR    ((uint32_t) 45UL)
#define NVIC_STIR_R_INTID_ADC1SEQ0    ((uint32_t) 46UL)
#define NVIC_STIR_R_INTID_ADC1SEQ1    ((uint32_t) 47UL)
#define NVIC_STIR_R_INTID_ADC1SEQ2    ((uint32_t) 48UL)
#define NVIC_STIR_R_INTID_ADC1SEQ3    ((uint32_t) 49UL)
#define NVIC_STIR_R_INTID_EPI0    ((uint32_t) 50UL)
#define NVIC_STIR_R_INTID_GPIOJ    ((uint32_t) 51UL)
#define NVIC_STIR_R_INTID_GPIOK    ((uint32_t) 52UL)
#define NVIC_STIR_R_INTID_GPIOL    ((uint32_t) 53UL)
#define NVIC_STIR_R_INTID_SSI2    ((uint32_t) 54UL)
#define NVIC_STIR_R_INTID_SSI3    ((uint32_t) 55UL)
#define NVIC_STIR_R_INTID_UART3    ((uint32_t) 56UL)
#define NVIC_STIR_R_INTID_UART4    ((uint32_t) 57UL)
#define NVIC_STIR_R_INTID_UART5    ((uint32_t) 58UL)
#define NVIC_STIR_R_INTID_UART6    ((uint32_t) 59UL)
#define NVIC_STIR_R_INTID_UART7    ((uint32_t) 60UL)
#define NVIC_STIR_R_INTID_I2C2    ((uint32_t) 61UL)
#define NVIC_STIR_R_INTID_I2C3    ((uint32_t) 62UL)
#define NVIC_STIR_R_INTID_TIMER4A    ((uint32_t) 63UL)
#define NVIC_STIR_R_INTID_TIMER4B    ((uint32_t) 64UL)
#define NVIC_STIR_R_INTID_TIMER5A    ((uint32_t) 65UL)
#define NVIC_STIR_R_INTID_TIMER5B    ((uint32_t) 66UL)
#define NVIC_STIR_R_INTID_SYSEXC    ((uint32_t) 67UL)
#define NVIC_STIR_R_INTID_RES84    ((uint32_t) 68UL)
#define NVIC_STIR_R_INTID_RES85    ((uint32_t) 69UL)
#define NVIC_STIR_R_INTID_I2C4    ((uint32_t) 70UL)
#define NVIC_STIR_R_INTID_I2C5    ((uint32_t) 71UL)
#define NVIC_STIR_R_INTID_GPIOM    ((uint32_t) 72UL)
#define NVIC_STIR_R_INTID_GPION    ((uint32_t) 73UL)
#define NVIC_STIR_R_INTID_RES90    ((uint32_t) 74UL)
#define NVIC_STIR_R_INTID_TAMPER    ((uint32_t) 75UL)
#define NVIC_STIR_R_INTID_GPIOP    ((uint32_t) 76UL)
#define NVIC_STIR_R_INTID_GPIOP1    ((uint32_t) 77UL)
#define NVIC_STIR_R_INTID_GPIOP2    ((uint32_t) 78UL)
#define NVIC_STIR_R_INTID_GPIOP3    ((uint32_t) 79UL)
#define NVIC_STIR_R_INTID_GPIOP4    ((uint32_t) 80UL)
#define NVIC_STIR_R_INTID_GPIOP5    ((uint32_t) 81UL)
#define NVIC_STIR_R_INTID_GPIOP6    ((uint32_t) 82UL)
#define NVIC_STIR_R_INTID_GPIOP7    ((uint32_t) 83UL)
#define NVIC_STIR_R_INTID_GPIOQ    ((uint32_t) 84UL)
#define NVIC_STIR_R_INTID_GPIOQ1    ((uint32_t) 85UL)
#define NVIC_STIR_R_INTID_GPIOQ2    ((uint32_t) 86UL)
#define NVIC_STIR_R_INTID_GPIOQ3    ((uint32_t) 87UL)
#define NVIC_STIR_R_INTID_GPIOQ4    ((uint32_t) 88UL)
#define NVIC_STIR_R_INTID_GPIOQ5    ((uint32_t) 89UL)
#define NVIC_STIR_R_INTID_GPIOQ6    ((uint32_t) 90UL)
#define NVIC_STIR_R_INTID_GPIOQ7    ((uint32_t) 91UL)
#define NVIC_STIR_R_INTID_GPIOR    ((uint32_t) 92UL)
#define NVIC_STIR_R_INTID_GPIOS    ((uint32_t) 93UL)
#define NVIC_STIR_R_INTID_SHA_MD5    ((uint32_t) 94UL)
#define NVIC_STIR_R_INTID_AES    ((uint32_t) 95UL)
#define NVIC_STIR_R_INTID_DES    ((uint32_t) 96UL)
#define NVIC_STIR_R_INTID_LCD    ((uint32_t) 97UL)
#define NVIC_STIR_R_INTID_TIMER6A    ((uint32_t) 98UL)
#define NVIC_STIR_R_INTID_TIMER6B    ((uint32_t) 99UL)
#define NVIC_STIR_R_INTID_TIMER7A    ((uint32_t) 100UL)
#define NVIC_STIR_R_INTID_TIMER7B    ((uint32_t) 101UL)
#define NVIC_STIR_R_INTID_I2C6    ((uint32_t) 102UL)
#define NVIC_STIR_R_INTID_I2C7    ((uint32_t) 103UL)
#define NVIC_STIR_R_INTID_KEYBOARD    ((uint32_t) 104UL)
#define NVIC_STIR_R_INTID_ONEWIRE    ((uint32_t) 105UL)
#define NVIC_STIR_R_INTID_PS2    ((uint32_t) 106UL)
#define NVIC_STIR_R_INTID_LEDSEQ    ((uint32_t) 107UL)
#define NVIC_STIR_R_INTID_IR    ((uint32_t) 108UL)
#define NVIC_STIR_R_INTID_I2C8    ((uint32_t) 109UL)
#define NVIC_STIR_R_INTID_I2C9    ((uint32_t) 110UL)
#define NVIC_STIR_R_INTID_GPIOT    ((uint32_t) 111UL)
#define NVIC_STIR_R_INTID_FAN    ((uint32_t) 112UL)
#define NVIC_STIR_R_INTID_RES129    ((uint32_t) 113UL)

#define NVIC_STIR_INTID_MASK    ((uint32_t) 0x000000FFUL)
#define NVIC_STIR_INTID_GPIOA    ((uint32_t) 0UL)
#define NVIC_STIR_INTID_GPIOB    ((uint32_t) 1UL)
#define NVIC_STIR_INTID_GPIOC    ((uint32_t) 2UL)
#define NVIC_STIR_INTID_GPIOD    ((uint32_t) 3UL)
#define NVIC_STIR_INTID_GPIOE    ((uint32_t) 4UL)
#define NVIC_STIR_INTID_UART0    ((uint32_t) 5UL)
#define NVIC_STIR_INTID_UART1    ((uint32_t) 6UL)
#define NVIC_STIR_INTID_SSI0    ((uint32_t) 7UL)
#define NVIC_STIR_INTID_I2C0    ((uint32_t) 8UL)
#define NVIC_STIR_INTID_PWM0FAULT    ((uint32_t) 9UL)
#define NVIC_STIR_INTID_PWM0GEN0    ((uint32_t) 10UL)
#define NVIC_STIR_INTID_PWM0GEN1    ((uint32_t) 11UL)
#define NVIC_STIR_INTID_PWM0GEN2    ((uint32_t) 12UL)
#define NVIC_STIR_INTID_QEI0    ((uint32_t) 13UL)
#define NVIC_STIR_INTID_ADC0SEQ0    ((uint32_t) 14UL)
#define NVIC_STIR_INTID_ADC0SEQ1    ((uint32_t) 15UL)
#define NVIC_STIR_INTID_ADC0SEQ2    ((uint32_t) 16UL)
#define NVIC_STIR_INTID_ADC0SEQ3    ((uint32_t) 17UL)
#define NVIC_STIR_INTID_WDT01    ((uint32_t) 18UL)
#define NVIC_STIR_INTID_TIMER0A    ((uint32_t) 19UL)
#define NVIC_STIR_INTID_TIMER0B    ((uint32_t) 20UL)
#define NVIC_STIR_INTID_TIMER1A    ((uint32_t) 21UL)
#define NVIC_STIR_INTID_TIMER1B    ((uint32_t) 22UL)
#define NVIC_STIR_INTID_TIMER2A    ((uint32_t) 23UL)
#define NVIC_STIR_INTID_TIMER2B    ((uint32_t) 24UL)
#define NVIC_STIR_INTID_ACMP0    ((uint32_t) 25UL)
#define NVIC_STIR_INTID_ACMP1    ((uint32_t) 26UL)
#define NVIC_STIR_INTID_ACMP2    ((uint32_t) 27UL)
#define NVIC_STIR_INTID_SYSCTL    ((uint32_t) 28UL)
#define NVIC_STIR_INTID_FLASH    ((uint32_t) 29UL)
#define NVIC_STIR_INTID_GPIOF    ((uint32_t) 30UL)
#define NVIC_STIR_INTID_GPIOG    ((uint32_t) 31UL)
#define NVIC_STIR_INTID_GPIOH    ((uint32_t) 32UL)
#define NVIC_STIR_INTID_UART2    ((uint32_t) 33UL)
#define NVIC_STIR_INTID_SSI1    ((uint32_t) 34UL)
#define NVIC_STIR_INTID_TIMER3A    ((uint32_t) 35UL)
#define NVIC_STIR_INTID_TIMER3B    ((uint32_t) 36UL)
#define NVIC_STIR_INTID_I2C1    ((uint32_t) 37UL)
#define NVIC_STIR_INTID_CAN0    ((uint32_t) 38UL)
#define NVIC_STIR_INTID_CAN1    ((uint32_t) 39UL)
#define NVIC_STIR_INTID_ETH    ((uint32_t) 40UL)
#define NVIC_STIR_INTID_HIB    ((uint32_t) 41UL)
#define NVIC_STIR_INTID_USB    ((uint32_t) 42UL)
#define NVIC_STIR_INTID_PWM0GEN3    ((uint32_t) 43UL)
#define NVIC_STIR_INTID_UDMASOFT    ((uint32_t) 44UL)
#define NVIC_STIR_INTID_UDMAERROR    ((uint32_t) 45UL)
#define NVIC_STIR_INTID_ADC1SEQ0    ((uint32_t) 46UL)
#define NVIC_STIR_INTID_ADC1SEQ1    ((uint32_t) 47UL)
#define NVIC_STIR_INTID_ADC1SEQ2    ((uint32_t) 48UL)
#define NVIC_STIR_INTID_ADC1SEQ3    ((uint32_t) 49UL)
#define NVIC_STIR_INTID_EPI0    ((uint32_t) 50UL)
#define NVIC_STIR_INTID_GPIOJ    ((uint32_t) 51UL)
#define NVIC_STIR_INTID_GPIOK    ((uint32_t) 52UL)
#define NVIC_STIR_INTID_GPIOL    ((uint32_t) 53UL)
#define NVIC_STIR_INTID_SSI2    ((uint32_t) 54UL)
#define NVIC_STIR_INTID_SSI3    ((uint32_t) 55UL)
#define NVIC_STIR_INTID_UART3    ((uint32_t) 56UL)
#define NVIC_STIR_INTID_UART4    ((uint32_t) 57UL)
#define NVIC_STIR_INTID_UART5    ((uint32_t) 58UL)
#define NVIC_STIR_INTID_UART6    ((uint32_t) 59UL)
#define NVIC_STIR_INTID_UART7    ((uint32_t) 60UL)
#define NVIC_STIR_INTID_I2C2    ((uint32_t) 61UL)
#define NVIC_STIR_INTID_I2C3    ((uint32_t) 62UL)
#define NVIC_STIR_INTID_TIMER4A    ((uint32_t) 63UL)
#define NVIC_STIR_INTID_TIMER4B    ((uint32_t) 64UL)
#define NVIC_STIR_INTID_TIMER5A    ((uint32_t) 65UL)
#define NVIC_STIR_INTID_TIMER5B    ((uint32_t) 66UL)
#define NVIC_STIR_INTID_SYSEXC    ((uint32_t) 67UL)
#define NVIC_STIR_INTID_RES84    ((uint32_t) 68UL)
#define NVIC_STIR_INTID_RES85    ((uint32_t) 69UL)
#define NVIC_STIR_INTID_I2C4    ((uint32_t) 70UL)
#define NVIC_STIR_INTID_I2C5    ((uint32_t) 71UL)
#define NVIC_STIR_INTID_GPIOM    ((uint32_t) 72UL)
#define NVIC_STIR_INTID_GPION    ((uint32_t) 73UL)
#define NVIC_STIR_INTID_RES90    ((uint32_t) 74UL)
#define NVIC_STIR_INTID_TAMPER    ((uint32_t) 75UL)
#define NVIC_STIR_INTID_GPIOP    ((uint32_t) 76UL)
#define NVIC_STIR_INTID_GPIOP1    ((uint32_t) 77UL)
#define NVIC_STIR_INTID_GPIOP2    ((uint32_t) 78UL)
#define NVIC_STIR_INTID_GPIOP3    ((uint32_t) 79UL)
#define NVIC_STIR_INTID_GPIOP4    ((uint32_t) 80UL)
#define NVIC_STIR_INTID_GPIOP5    ((uint32_t) 81UL)
#define NVIC_STIR_INTID_GPIOP6    ((uint32_t) 82UL)
#define NVIC_STIR_INTID_GPIOP7    ((uint32_t) 83UL)
#define NVIC_STIR_INTID_GPIOQ    ((uint32_t) 84UL)
#define NVIC_STIR_INTID_GPIOQ1    ((uint32_t) 85UL)
#define NVIC_STIR_INTID_GPIOQ2    ((uint32_t) 86UL)
#define NVIC_STIR_INTID_GPIOQ3    ((uint32_t) 87UL)
#define NVIC_STIR_INTID_GPIOQ4    ((uint32_t) 88UL)
#define NVIC_STIR_INTID_GPIOQ5    ((uint32_t) 89UL)
#define NVIC_STIR_INTID_GPIOQ6    ((uint32_t) 90UL)
#define NVIC_STIR_INTID_GPIOQ7    ((uint32_t) 91UL)
#define NVIC_STIR_INTID_GPIOR    ((uint32_t) 92UL)
#define NVIC_STIR_INTID_GPIOS    ((uint32_t) 93UL)
#define NVIC_STIR_INTID_SHA_MD5    ((uint32_t) 94UL)
#define NVIC_STIR_INTID_AES    ((uint32_t) 95UL)
#define NVIC_STIR_INTID_DES    ((uint32_t) 96UL)
#define NVIC_STIR_INTID_LCD    ((uint32_t) 97UL)
#define NVIC_STIR_INTID_TIMER6A    ((uint32_t) 98UL)
#define NVIC_STIR_INTID_TIMER6B    ((uint32_t) 99UL)
#define NVIC_STIR_INTID_TIMER7A    ((uint32_t) 100UL)
#define NVIC_STIR_INTID_TIMER7B    ((uint32_t) 101UL)
#define NVIC_STIR_INTID_I2C6    ((uint32_t) 102UL)
#define NVIC_STIR_INTID_I2C7    ((uint32_t) 103UL)
#define NVIC_STIR_INTID_KEYBOARD    ((uint32_t) 104UL)
#define NVIC_STIR_INTID_ONEWIRE    ((uint32_t) 105UL)
#define NVIC_STIR_INTID_PS2    ((uint32_t) 106UL)
#define NVIC_STIR_INTID_LEDSEQ    ((uint32_t) 107UL)
#define NVIC_STIR_INTID_IR    ((uint32_t) 108UL)
#define NVIC_STIR_INTID_I2C8    ((uint32_t) 109UL)
#define NVIC_STIR_INTID_I2C9    ((uint32_t) 110UL)
#define NVIC_STIR_INTID_GPIOT    ((uint32_t) 111UL)
#define NVIC_STIR_INTID_FAN    ((uint32_t) 112UL)
#define NVIC_STIR_INTID_RES129    ((uint32_t) 113UL)
/*-----------------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_STIR_H_ */
