/*
 * SYSTICK_TickAccumulated.h
 *
 *  Created on: 18 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_DRIVER_SYSTICK_TICKACCUMULATED_H_
#define XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_DRIVER_SYSTICK_TICKACCUMULATED_H_

#include <xDriver_MCU/Common/xHeader/MCU_Variables.h>

uint64_t SYSTICK__u64GetTickAccumulated(void);

#endif /* XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_DRIVER_SYSTICK_TICKACCUMULATED_H_ */
