/**
 *
 * @file ADC_RegisterAddress.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 oct. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 oct. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_ADC_PERIPHERAL_REGISTER_XHEADER_ADC_REGISTERADDRESS_H_
#define XDRIVER_MCU_ADC_PERIPHERAL_REGISTER_XHEADER_ADC_REGISTERADDRESS_H_

#include <xDriver_MCU/ADC/Peripheral/xHeader/ADC_Enum.h>

#define ADC_SS_REGISTER_NUM    ((UBase_t) 8UL)

#define ADC_BASE    ((UBase_t) 0x40038000UL)
#define ADC0_BASE    ((UBase_t) 0x40038000UL)
#define ADC1_BASE    ((UBase_t) 0x40039000UL)

#define ADC_OFFSET    ((UBase_t) 0x00038000UL)
#define ADC0_OFFSET    ((UBase_t) 0x00038000UL)
#define ADC1_OFFSET    ((UBase_t) 0x00039000UL)

#define ADC_BITBANDING_BASE    ((UBase_t) 0x42000000UL)

#define ADC_ACTSS_OFFSET    ((UBase_t) 0x0000UL)
#define ADC_RIS_OFFSET    ((UBase_t) 0x0004UL)
#define ADC_IM_OFFSET    ((UBase_t) 0x0008UL)
#define ADC_ISC_OFFSET    ((UBase_t) 0x000CUL)
#define ADC_OSTAT_OFFSET    ((UBase_t) 0x0010UL)
#define ADC_EMUX_OFFSET    ((UBase_t) 0x0014UL)
#define ADC_USTAT_OFFSET    ((UBase_t) 0x0018UL)
#define ADC_TSSEL_OFFSET    ((UBase_t) 0x001CUL)
#define ADC_SSPRI_OFFSET    ((UBase_t) 0x0020UL)
#define ADC_SPC_OFFSET    ((UBase_t) 0x0024UL)
#define ADC_PSSI_OFFSET    ((UBase_t) 0x0028UL)
#define ADC_SAC_OFFSET    ((UBase_t) 0x0030UL)
#define ADC_DCISC_OFFSET    ((UBase_t) 0x0034UL)
#define ADC_CTL_OFFSET    ((UBase_t) 0x0038UL)


#define ADC_SS_MUX_OFFSET    ((UBase_t) 0x0000UL)
#define ADC_SS_CTL_OFFSET    ((UBase_t) 0x0004UL)
#define ADC_SS_FIFO_OFFSET    ((UBase_t) 0x0008UL)
#define ADC_SS_FSTAT_OFFSET    ((UBase_t) 0x000CUL)
#define ADC_SS_OP_OFFSET    ((UBase_t) 0x0010UL)
#define ADC_SS_DC_OFFSET    ((UBase_t) 0x0014UL)
#define ADC_SS_EMUX_OFFSET    ((UBase_t) 0x0018UL)
#define ADC_SS_TSH_OFFSET    ((UBase_t) 0x001CUL)

#define ADC_SS_REGISTER_BASE_OFFSET    ((UBase_t) 0x0040UL)
#define ADC_SS_REGISTER_OFFSET    ((UBase_t) 0x0020UL)

#define ADC_SS0_MUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_MUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_CTL_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_CTL_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_FIFO_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_FIFO_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_FSTAT_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_FSTAT_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_OP_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_OP_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_DC_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_DC_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_EMUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_EMUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS0_TSH_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 0UL) + ADC_SS_TSH_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))

#define ADC_SS1_MUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_MUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_CTL_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_CTL_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_FIFO_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_FIFO_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_FSTAT_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_FSTAT_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_OP_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_OP_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_DC_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_DC_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_EMUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_EMUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS1_TSH_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 1UL) + ADC_SS_TSH_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))

#define ADC_SS2_MUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_MUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_CTL_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_CTL_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_FIFO_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_FIFO_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_FSTAT_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_FSTAT_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_OP_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_OP_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_DC_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_DC_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_EMUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_EMUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS2_TSH_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 2UL) + ADC_SS_TSH_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))

#define ADC_SS3_MUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_MUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_CTL_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_CTL_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_FIFO_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_FIFO_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_FSTAT_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_FSTAT_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_OP_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_OP_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_DC_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_DC_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_EMUX_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_EMUX_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))
#define ADC_SS3_TSH_OFFSET    ((UBase_t) ((ADC_SS_REGISTER_OFFSET * 3UL) + ADC_SS_TSH_OFFSET + ADC_SS_REGISTER_BASE_OFFSET))

#define ADC_DC_RIC_OFFSET    ((UBase_t) 0x0D00UL)

#define ADC_DC_CTL_OFFSET    ((UBase_t) 0x0E00UL)
#define ADC_DC0_CTL_OFFSET    ((UBase_t) 0x0E00UL)
#define ADC_DC1_CTL_OFFSET    ((UBase_t) 0x0E04UL)
#define ADC_DC2_CTL_OFFSET    ((UBase_t) 0x0E08UL)
#define ADC_DC3_CTL_OFFSET    ((UBase_t) 0x0E0CUL)
#define ADC_DC4_CTL_OFFSET    ((UBase_t) 0x0E10UL)
#define ADC_DC5_CTL_OFFSET    ((UBase_t) 0x0E14UL)
#define ADC_DC6_CTL_OFFSET    ((UBase_t) 0x0E18UL)
#define ADC_DC7_CTL_OFFSET    ((UBase_t) 0x0E1CUL)

#define ADC_DC_CMP_OFFSET    ((UBase_t) 0x0E40UL)
#define ADC_DC0_CMP_OFFSET    ((UBase_t) 0x0E40UL)
#define ADC_DC1_CMP_OFFSET    ((UBase_t) 0x0E44UL)
#define ADC_DC2_CMP_OFFSET    ((UBase_t) 0x0E48UL)
#define ADC_DC3_CMP_OFFSET    ((UBase_t) 0x0E4CUL)
#define ADC_DC4_CMP_OFFSET    ((UBase_t) 0x0E50UL)
#define ADC_DC5_CMP_OFFSET    ((UBase_t) 0x0E54UL)
#define ADC_DC6_CMP_OFFSET    ((UBase_t) 0x0E58UL)
#define ADC_DC7_CMP_OFFSET    ((UBase_t) 0x0E5CUL)

#define ADC_PP_OFFSET    ((UBase_t) 0x0FC0UL)
#define ADC_PC_OFFSET    ((UBase_t) 0x0FC4UL)
#define ADC_CC_OFFSET    ((UBase_t) 0x0FC8UL)

#endif /* XDRIVER_MCU_ADC_PERIPHERAL_REGISTER_XHEADER_ADC_REGISTERADDRESS_H_ */
