/**
 *
 * @file DMA_RegisterPeripheral_Bitbanding.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 28 jul. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description * 28 jul. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_
#define XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_

#include <xDriver_MCU/DMA/Peripheral/Register/xHeader/DMA_RegisterAddress.h>
#include <xDriver_MCU/DMA/Peripheral/Register/RegisterDefines/DMA_RegisterDefines.h>
#include <xDriver_MCU/DMA/Peripheral/Struct/xHeader/DMA_StructPeripheral_Bitbanding.h>

#define DMA_BITBANDING    ((DMA_BITBANDING_t*) (DMA_BITBANDING_BASE + (DMA_OFFSET * 32UL)))

/********************************************************************************************
************************************** 4 STAT **********************************************
********************************************************************************************/
#define DMA_BITBANDING_STAT    ((DMA_BITBANDING_STAT_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_STAT_OFFSET) * 32UL)))

#define DMA_BITBANDING_STAT_MASTEN    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_STAT_OFFSET) * 32UL) + (DMA_STAT_R_MASTEN_BIT * 4UL))))

/********************************************************************************************
************************************** 5 CFG **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CFG    ((DMA_BITBANDING_CFG_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CFG_OFFSET) * 32UL)))

#define DMA_BITBANDING_CFG_MASTEN    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CFG_OFFSET) * 32UL) + (DMA_CFG_R_MASTEN_BIT * 4UL))))

/********************************************************************************************
************************************** 6 CTLBASE **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CTLBASE    ((DMA_BITBANDING_CTLBASE_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CTLBASE_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 7 ALTBASE **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ALTBASE    ((DMA_BITBANDING_ALTBASE_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTBASE_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 8 WAITSTAT **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_WAITSTAT    ((DMA_BITBANDING_CH_WAITSTAT_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ0    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ0_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ1    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ1_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ2    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ2_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ3    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ3_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ4    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ4_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ5    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ5_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ6    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ6_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ7    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ7_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ8    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ8_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ9    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ9_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ10    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ10_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ11    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ11_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ12    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ12_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ13    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ13_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ14    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ14_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ15    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ15_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ16    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ16_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ17    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ17_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ18    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ18_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ19    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ19_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ20    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ20_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ21    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ21_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ22    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ22_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ23    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ23_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ24    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ24_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ25    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ25_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ26    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ26_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ27    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ27_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ28    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ28_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ29    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ29_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ30    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ30_BIT * 4UL))))
#define DMA_BITBANDING_CH_WAITSTAT_WAITREQ31    (*((volatile const UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_WAITSTAT_OFFSET) * 32UL) + (DMA_CH_WAITSTAT_R_WAITREQ31_BIT * 4UL))))

/********************************************************************************************
************************************** 9 SWREQ **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_SWREQ    ((DMA_BITBANDING_CH_SWREQ_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_SWREQ_SWREQ0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ0_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ1_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ2_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ3_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ4_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ5_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ6_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ7_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ8_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ9_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ10_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ11_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ12_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ13_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ14_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ15_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ16_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ17_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ18_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ19_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ20_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ21_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ22_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ23_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ24_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ25_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ26_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ27_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ28_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ29_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ30_BIT * 4UL))))
#define DMA_BITBANDING_CH_SWREQ_SWREQ31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_SWREQ_OFFSET) * 32UL) + (DMA_CH_SWREQ_R_SWREQ31_BIT * 4UL))))

/********************************************************************************************
************************************** 10 USEBURSTSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_USEBURSTSET    ((DMA_BITBANDING_CH_SET_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_USEBURSTSET_SET0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTSET_SET31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTSET_OFFSET) * 32UL) + (DMA_CH_USEBURSTSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 11 USEBURSTCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_USEBURSTCLR    ((DMA_BITBANDING_CH_CLR_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_USEBURSTCLR_CLR0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_CH_USEBURSTCLR_CLR31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_USEBURSTCLR_OFFSET) * 32UL) + (DMA_CH_USEBURSTCLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************** 12 REQMASKSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_REQMASKSET    ((DMA_BITBANDING_CH_SET_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_REQMASKSET_SET0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKSET_SET31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKSET_OFFSET) * 32UL) + (DMA_CH_REQMASKSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 13 REQMASKCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_REQMASKCLR    ((DMA_BITBANDING_CH_CLR_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_REQMASKCLR_CLR0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_CH_REQMASKCLR_CLR31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_REQMASKCLR_OFFSET) * 32UL) + (DMA_CH_REQMASKCLR_R_CLR31_BIT * 4UL))))


/********************************************************************************************
************************************** 14 ENASET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_ENASET    ((DMA_BITBANDING_CH_SET_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_ENASET_SET0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENASET_SET31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENASET_OFFSET) * 32UL) + (DMA_CH_ENASET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 15 ENACLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_ENACLR    ((DMA_BITBANDING_CH_CLR_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_ENACLR_CLR0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_CH_ENACLR_CLR31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ENACLR_OFFSET) * 32UL) + (DMA_CH_ENACLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************** 16 ALTSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_ALTSET    ((DMA_BITBANDING_CH_SET_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_ALTSET_SET0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTSET_SET31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTSET_OFFSET) * 32UL) + (DMA_CH_ALTSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 17 ALTCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_ALTCLR    ((DMA_BITBANDING_CH_CLR_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_ALTCLR_CLR0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_CH_ALTCLR_CLR31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ALTCLR_OFFSET) * 32UL) + (DMA_CH_ALTCLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************* 18 PRIOSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_PRIOSET    ((DMA_BITBANDING_CH_SET_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_PRIOSET_SET0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOSET_SET31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOSET_OFFSET) * 32UL) + (DMA_CH_PRIOSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 19 PRIOCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_PRIOCLR    ((DMA_BITBANDING_CH_CLR_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_PRIOCLR_CLR0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_CH_PRIOCLR_CLR31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_PRIOCLR_OFFSET) * 32UL) + (DMA_CH_PRIOCLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************** 20 ERRCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ERRCLR    ((DMA_BITBANDING_ERRCLR_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ERRCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_ERRCLR_ERRCLR    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ERRCLR_OFFSET) * 32UL) + (DMA_ERRCLR_R_ERRCLR_BIT * 4UL))))

/********************************************************************************************
************************************** 21 CHASGN **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_ASGN    ((DMA_BITBANDING_CH_ASGN_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_ASGN_ASGN0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN0_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN1_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN2_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN3_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN4_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN5_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN6_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN7_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN8_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN9_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN10_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN11_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN12_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN13_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN14_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN15_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN16_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN17_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN18_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN19_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN20_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN21_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN22_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN23_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN24_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN25_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN26_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN27_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN28_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN29_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN30_BIT * 4UL))))
#define DMA_BITBANDING_CH_ASGN_ASGN31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_ASGN_OFFSET) * 32UL) + (DMA_CH_ASGN_R_ASGN31_BIT * 4UL))))

/********************************************************************************************
************************************** 22 CHIS **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_IS    ((DMA_BITBANDING_CH_IS_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL)))

#define DMA_BITBANDING_CH_IS_IS0    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS0_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS1    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS1_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS2    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS2_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS3    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS3_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS4    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS4_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS5    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS5_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS6    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS6_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS7    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS7_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS8    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS8_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS9    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS9_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS10    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS10_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS11    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS11_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS12    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS12_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS13    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS13_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS14    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS14_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS15    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS15_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS16    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS16_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS17    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS17_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS18    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS18_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS19    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS19_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS20    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS20_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS21    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS21_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS22    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS22_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS23    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS23_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS24    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS24_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS25    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS25_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS26    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS26_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS27    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS27_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS28    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS28_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS29    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS29_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS30    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS30_BIT * 4UL))))
#define DMA_BITBANDING_CH_IS_IS31    (*((volatile UBase_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_IS_OFFSET) * 32UL) + (DMA_CH_IS_R_IS31_BIT * 4UL))))

/********************************************************************************************
************************************** 23 CHMAP0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_MAP0    ((DMA_BITBANDING_CH_MAP0_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_MAP0_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 24 CHMAP1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_MAP1    ((DMA_BITBANDING_CH_MAP1_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_MAP1_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 25 CHMAP2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_MAP2    ((DMA_BITBANDING_CH_MAP2_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_MAP2_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 26 CHMAP3 *********************************************
********************************************************************************************/
#define DMA_BITBANDING_CH_MAP3    ((DMA_BITBANDING_CH_MAP3_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CH_MAP3_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 27 PeriphID0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID0    ((DMA_BITBANDING_PeriphID0_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID0_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 28 PeriphID1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID1    ((DMA_BITBANDING_PeriphID1_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID1_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 29 PeriphID2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID2    ((DMA_BITBANDING_PeriphID2_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID2_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 30 PeriphID3 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID3    ((DMA_BITBANDING_PeriphID3_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID3_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 31 PeriphID4 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID4    ((DMA_BITBANDING_PeriphID4_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID4_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 32 PCellID0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID0    ((DMA_BITBANDING_PCellID0_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID0_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 33 PCellID1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID1    ((DMA_BITBANDING_PCellID1_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID1_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 34 PCellID2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID2    ((DMA_BITBANDING_PCellID2_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID2_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 35 PCellID3 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID3    ((DMA_BITBANDING_PCellID3_t*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID3_OFFSET) * 32UL)))

#endif /* XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_ */
