/**
 *
 * @file DMA_RegisterPeripheralChannel_Bitbanding.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 29 jul. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 29 jul. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERALCHANNEL_BITBANDING_H_
#define XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERALCHANNEL_BITBANDING_H_

#include <xDriver_MCU/DMA/Peripheral/Register/xHeader/DMA_RegisterAddressChannel.h>
#include <xDriver_MCU/DMA/Peripheral/Register/RegisterDefines/DMA_RegisterDefines.h>
#include <xDriver_MCU/DMA/Peripheral/Struct/xHeader/DMA_StructPeripheralChannel_Bitbanding.h>

#define DMA_CH_PRIMARY_BITBANDING    ((DMA_CH_BITBANDING_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + (DMA_CH_PRIMARY_OFFSET * (uint32_t) 32UL)))
#define DMA_CH_ALTERNATE_BITBANDING    ((DMA_CH_BITBANDING_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + (DMA_CH_ALTERNATE_OFFSET * (uint32_t) 32UL)))

/********************************************************************************************
************************************** 1 SRCENDP **********************************************
********************************************************************************************/
#define DMA_CH0_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH0_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH1_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH1_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH2_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH2_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH3_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH3_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH4_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH4_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH5_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH5_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH6_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH6_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH7_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH7_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH8_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH8_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH9_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH9_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH10_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH10_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH11_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH11_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH12_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH12_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH13_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH13_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH14_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH14_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH15_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH15_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH16_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH16_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH17_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH17_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH18_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH18_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH19_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH19_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH20_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH20_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH21_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH21_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH22_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH22_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH23_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH23_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH24_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH24_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH25_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH25_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH26_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH26_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH27_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH27_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH28_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH28_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH29_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH29_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH30_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH30_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH31_PRIMARY_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH31_PRIMARY_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** ALT 1 SRCENDP **********************************************
********************************************************************************************/
#define DMA_CH0_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH0_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH1_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH1_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH2_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH2_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH3_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH3_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH4_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH4_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH5_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH5_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH6_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH6_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH7_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH7_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH8_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH8_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH9_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH9_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH10_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH10_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH11_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH11_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH12_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH12_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH13_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH13_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH14_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH14_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH15_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH15_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH16_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH16_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH17_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH17_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH18_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH18_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH19_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH19_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH20_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH20_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH21_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH21_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH22_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH22_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH23_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH23_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH24_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH24_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH25_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH25_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH26_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH26_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH27_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH27_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH28_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH28_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH29_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH29_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH30_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH30_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH31_ALTERNATE_BITBANDING_SRCENDP    ((DMA_CH_BITBANDING_SRCENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH31_ALTERNATE_OFFSET + DMA_CH_SRCENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** 2 DSTENDP **********************************************
********************************************************************************************/
#define DMA_CH0_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH0_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH1_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH1_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH2_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH2_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH3_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH3_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH4_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH4_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH5_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH5_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH6_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH6_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH7_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH7_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH8_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH8_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH9_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH9_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH10_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH10_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH11_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH11_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH12_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH12_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH13_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH13_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH14_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH14_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH15_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH15_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH16_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH16_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH17_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH17_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH18_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH18_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH19_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH19_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH20_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH20_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH21_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH21_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH22_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH22_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH23_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH23_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH24_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH24_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH25_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH25_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH26_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH26_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH27_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH27_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH28_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH28_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH29_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH29_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH30_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH30_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH31_PRIMARY_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH31_PRIMARY_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** ALT 2 DSTENDP **********************************************
********************************************************************************************/
#define DMA_CH0_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH0_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH1_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH1_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH2_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH2_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH3_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH3_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH4_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH4_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH5_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH5_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH6_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH6_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH7_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH7_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH8_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH8_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH9_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH9_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH10_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH10_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH11_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH11_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH12_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH12_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH13_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH13_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH14_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH14_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH15_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH15_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH16_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH16_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH17_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH17_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH18_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH18_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH19_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH19_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH20_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH20_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH21_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH21_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH22_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH22_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH23_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH23_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH24_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH24_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH25_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH25_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH26_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH26_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH27_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH27_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH28_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH28_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH29_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH29_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH30_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH30_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH31_ALTERNATE_BITBANDING_DSTENDP    ((DMA_CH_BITBANDING_DSTENDP_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH31_ALTERNATE_OFFSET + DMA_CH_DSTENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** 3 CTL **********************************************
********************************************************************************************/
#define DMA_CH0_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH0_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH1_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH1_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH2_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH2_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH3_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH3_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH4_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH4_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH5_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH5_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH6_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH6_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH7_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH7_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH8_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH8_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH9_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH9_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH10_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH10_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH11_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH11_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH12_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH12_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH13_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH13_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH14_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH14_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH15_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH15_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH16_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH16_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH17_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH17_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH18_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH18_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH19_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH19_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH20_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH20_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH21_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH21_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH22_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH22_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH23_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH23_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH24_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH24_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH25_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH25_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH26_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH26_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH27_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH27_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH28_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH28_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH29_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH29_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH30_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH30_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH31_PRIMARY_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_PRIMARY_BITBANDING_BASE + ((DMA_CH31_PRIMARY_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** ALT 3 CTL **********************************************
********************************************************************************************/
#define DMA_CH0_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH0_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH1_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH1_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH2_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH2_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH3_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH3_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH4_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH4_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH5_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH5_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH6_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH6_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH7_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH7_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH8_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH8_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH9_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH9_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH10_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH10_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH11_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH11_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH12_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH12_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH13_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH13_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH14_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH14_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH15_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH15_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH16_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH16_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH17_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH17_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH18_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH18_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH19_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH19_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH20_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH20_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH21_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH21_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH22_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH22_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH23_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH23_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH24_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH24_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH25_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH25_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH26_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH26_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH27_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH27_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH28_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH28_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH29_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH29_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH30_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH30_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))
#define DMA_CH31_ALTERNATE_BITBANDING_CTL    ((DMA_CH_BITBANDING_CTL_t*) ((uint32_t) DMA_CH_ALTERNATE_BITBANDING_BASE + ((DMA_CH31_ALTERNATE_OFFSET + DMA_CH_CTL_OFFSET) * (uint32_t) 32UL)))


#endif /* XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERALCHANNEL_BITBANDING_H_ */
