/**
 *
 * @file NVIC_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 19 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 19 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Variables.h>


typedef enum
{
    NVIC_enERROR_OK = (uint32_t) MCU_enERROR_OK,
    NVIC_enERROR_POINTER = (uint32_t) MCU_enERROR_POINTER,
    NVIC_enERROR_VALUE = (uint32_t) MCU_enERROR_VALUE,
    NVIC_enERROR_UNDEF = (uint32_t) MCU_enERROR_UNDEF,
}NVIC_enERROR;

typedef enum
{
    NVIC_enSTATE_DIS = (uint32_t) MCU_enSTATE_DIS,
    NVIC_enSTATE_ENA = (uint32_t) MCU_enSTATE_ENA,
    NVIC_enSTATE_UNDEF = (uint32_t) MCU_enSTATE_UNDEF,
}NVIC_nSTATE;

typedef enum
{
    NVIC_enNOPENDING = 0UL,
    NVIC_enPENDING = 1UL,
}NVIC_nPENDSTATE;

typedef enum
{
    NVIC_enSTATUS_INACTIVE = (uint32_t) MCU_enSTATUS_INACTIVE,
    NVIC_enSTATUS_ACTIVE = (uint32_t) MCU_enSTATUS_ACTIVE,
    NVIC_enSTATUS_UNDEF = (uint32_t) MCU_enSTATUS_UNDEF,
}NVIC_nSTATUS;

typedef enum
{
    NVIC_enPRI0 = (uint32_t) MCU_enPRI0,
    NVIC_enPRI1 = (uint32_t) MCU_enPRI1,
    NVIC_enPRI2 = (uint32_t) MCU_enPRI2,
    NVIC_enPRI3 = (uint32_t) MCU_enPRI3,
    NVIC_enPRI4 = (uint32_t) MCU_enPRI4,
    NVIC_enPRI5 = (uint32_t) MCU_enPRI5,
    NVIC_enPRI6 = (uint32_t) MCU_enPRI6,
    NVIC_enPRI7 = (uint32_t) MCU_enPRI7,
    NVIC_enPRIMAX = (uint32_t) MCU_enPRIMAX,
    NVIC_enDEFAULT = (uint32_t) MCU_enDEFAULT,
}NVIC_nPRIORITY;

typedef enum
{
    NVIC_enMODULE_0 = 0UL,
    NVIC_enMODULE_MAX = 1UL,
}NVIC_nMODULE;

typedef enum
{
     NVIC_enVECTOR_GPIOA = 0UL,
     NVIC_enVECTOR_GPIOB = 1UL,
     NVIC_enVECTOR_GPIOC = 2UL,
     NVIC_enVECTOR_GPIOD = 3UL,
     NVIC_enVECTOR_GPIOE = 4UL,
     NVIC_enVECTOR_UART0 = 5UL,
     NVIC_enVECTOR_UART1 = 6UL,
     NVIC_enVECTOR_SSI0 = 7UL,
     NVIC_enVECTOR_I2C0 = 8UL,
     NVIC_enVECTOR_PWM0FAULT = 9UL,
     NVIC_enVECTOR_PWM0GEN0 = 10UL,
     NVIC_enVECTOR_PWM0GEN1 = 11UL,
     NVIC_enVECTOR_PWM0GEN2 = 12UL,
     NVIC_enVECTOR_QEI0 = 13UL,
     NVIC_enVECTOR_ADC0SEQ0 = 14UL,
     NVIC_enVECTOR_ADC0SEQ1 = 15UL,
     NVIC_enVECTOR_ADC0SEQ2 = 16UL,
     NVIC_enVECTOR_ADC0SEQ3 = 17UL,
     NVIC_enVECTOR_WDT01 = 18UL,
     NVIC_enVECTOR_TIMER0A = 19UL,
     NVIC_enVECTOR_TIMER0B = 20UL,
     NVIC_enVECTOR_TIMER1A = 21UL,
     NVIC_enVECTOR_TIMER1B = 22UL,
     NVIC_enVECTOR_TIMER2A = 23UL,
     NVIC_enVECTOR_TIMER2B = 24UL,
     NVIC_enVECTOR_ACMP0 = 25UL,
     NVIC_enVECTOR_ACMP1 = 26UL,
     NVIC_enVECTOR_ACMP2 = 27UL,
     NVIC_enVECTOR_SYSCTL = 28UL,
     NVIC_enVECTOR_FLASH = 29UL,
     NVIC_enVECTOR_GPIOF = 30UL,
     NVIC_enVECTOR_GPIOG = 31UL,
     NVIC_enVECTOR_GPIOH = 32UL,
     NVIC_enVECTOR_UART2 = 33UL,
     NVIC_enVECTOR_SSI1 = 34UL,
     NVIC_enVECTOR_TIMER3A = 35UL,
     NVIC_enVECTOR_TIMER3B = 36UL,
     NVIC_enVECTOR_I2C1 = 37UL,
     NVIC_enVECTOR_CAN0 = 38UL,
     NVIC_enVECTOR_CAN1 = 39UL,
     NVIC_enVECTOR_ETH = 40UL,
     NVIC_enVECTOR_HIB = 41UL,
     NVIC_enVECTOR_USB = 42UL,
     NVIC_enVECTOR_PWM0GEN3 = 43UL,
     NVIC_enVECTOR_UDMASOFT = 44UL,
     NVIC_enVECTOR_UDMAERROR = 45UL,
     NVIC_enVECTOR_ADC1SEQ0 = 46UL,
     NVIC_enVECTOR_ADC1SEQ1 = 47UL,
     NVIC_enVECTOR_ADC1SEQ2 = 48UL,
     NVIC_enVECTOR_ADC1SEQ3 = 49UL,
     NVIC_enVECTOR_EPI0 = 50UL,
     NVIC_enVECTOR_GPIOJ = 51UL,
     NVIC_enVECTOR_GPIOK = 52UL,
     NVIC_enVECTOR_GPIOL = 53UL,
     NVIC_enVECTOR_SSI2 = 54UL,
     NVIC_enVECTOR_SSI3 = 55UL,
     NVIC_enVECTOR_UART3 = 56UL,
     NVIC_enVECTOR_UART4 = 57UL,
     NVIC_enVECTOR_UART5 = 58UL,
     NVIC_enVECTOR_UART6 = 59UL,
     NVIC_enVECTOR_UART7 = 60UL,
     NVIC_enVECTOR_I2C2 = 61UL,
     NVIC_enVECTOR_I2C3 = 62UL,
     NVIC_enVECTOR_TIMER4A = 63UL,
     NVIC_enVECTOR_TIMER4B = 64UL,
     NVIC_enVECTOR_TIMER5A = 65UL,
     NVIC_enVECTOR_TIMER5B = 66UL,
     NVIC_enVECTOR_SYSEXC = 67UL,
     NVIC_enVECTOR_RES84 = 68UL,
     NVIC_enVECTOR_RES85 = 69UL,
     NVIC_enVECTOR_I2C4 = 70UL,
     NVIC_enVECTOR_I2C5 = 71UL,
     NVIC_enVECTOR_GPIOM = 72UL,
     NVIC_enVECTOR_GPION = 73UL,
     NVIC_enVECTOR_RES90 = 74UL,
     NVIC_enVECTOR_TAMPER = 75UL,
     NVIC_enVECTOR_GPIOP = 76UL,
     NVIC_enVECTOR_GPIOP1 = 77UL,
     NVIC_enVECTOR_GPIOP2 = 78UL,
     NVIC_enVECTOR_GPIOP3 = 79UL,
     NVIC_enVECTOR_GPIOP4 = 80UL,
     NVIC_enVECTOR_GPIOP5 = 81UL,
     NVIC_enVECTOR_GPIOP6 = 82UL,
     NVIC_enVECTOR_GPIOP7 = 83UL,
     NVIC_enVECTOR_GPIOQ = 84UL,
     NVIC_enVECTOR_GPIOQ1 = 85UL,
     NVIC_enVECTOR_GPIOQ2 = 86UL,
     NVIC_enVECTOR_GPIOQ3 = 87UL,
     NVIC_enVECTOR_GPIOQ4 = 88UL,
     NVIC_enVECTOR_GPIOQ5 = 89UL,
     NVIC_enVECTOR_GPIOQ6 = 90UL,
     NVIC_enVECTOR_GPIOQ7 = 91UL,
     NVIC_enVECTOR_GPIOR = 92UL,
     NVIC_enVECTOR_GPIOS = 93UL,
     NVIC_enVECTOR_SHA_MD5 = 94UL,
     NVIC_enVECTOR_AES = 95UL,
     NVIC_enVECTOR_DES = 96UL,
     NVIC_enVECTOR_LCD = 97UL,
     NVIC_enVECTOR_TIMER6A = 98UL,
     NVIC_enVECTOR_TIMER6B = 99UL,
     NVIC_enVECTOR_TIMER7A = 100UL,
     NVIC_enVECTOR_TIMER7B = 101UL,
     NVIC_enVECTOR_I2C6 = 102UL,
     NVIC_enVECTOR_I2C7 = 103UL,
     NVIC_enVECTOR_KEYBOARD = 104UL,
     NVIC_enVECTOR_ONEWIRE = 105UL,
     NVIC_enVECTOR_PS2 = 106UL,
     NVIC_enVECTOR_LEDSEQ = 107UL,
     NVIC_enVECTOR_IR = 108UL,
     NVIC_enVECTOR_I2C8 = 109UL,
     NVIC_enVECTOR_I2C9 = 110UL,
     NVIC_enVECTOR_GPIOT = 111UL,
     NVIC_enVECTOR_FAN = 112UL,
     NVIC_enVECTOR_RES129 = 113UL,
}NVIC_nVECTOR;

typedef enum
{
/******  Cortex-M4 Processor Exceptions Numbers ****************************************************************/
      ThreadMode_IRQn = -16,
      Reset_IRQn = -15,
      NonMaskableInt_IRQn = -14,    /*!< 2 Non Maskable Interrupt                                          */
      HardFault_IRQn = -13,
      MemoryManagement_IRQn = -12,    /*!< 4 Cortex-M4 Memory Management Interrupt                           */
      BusFault_IRQn = -11,    /*!< 5 Cortex-M4 Bus Fault Interrupt                                   */
      UsageFault_IRQn = -10,    /*!< 6 Cortex-M4 Usage Fault Interrupt                                 */
      SVCall_IRQn = -5,     /*!< 11 Cortex-M4 SV Call Interrupt                                    */
      DebugMonitor_IRQn = -4,     /*!< 12 Cortex-M4 Debug Monitor Interrupt                              */
      PendSV_IRQn = -2,     /*!< 14 Cortex-M4 Pend SV Interrupt                                    */
      SYSTICK_IRQn = -1,     /*!< 15 Cortex-M4 System Tick Interrupt                                */
/******  TM4C specific Interrupt Numbers **********************************************************************/
      GPIOA_IRQn = 0,
      GPIOB_IRQn = 1,
      GPIOC_IRQn = 2,
      GPIOD_IRQn = 3,
      GPIOE_IRQn = 4,
      UART0_IRQn = 5,
      UART1_IRQn = 6,
      SSI0_IRQn = 7,
      I2C0_IRQn = 8,
      PWM0FAULT_IRQn = 9,
      PWM0GEN0_IRQn = 10,
      PWM0GEN1_IRQn = 11,
      PWM0GEN2_IRQn = 12,
      QEI0_IRQn = 13,
      ADC0SEQ0_IRQn = 14,
      ADC0SEQ1_IRQn = 15,
      ADC0SEQ2_IRQn = 16,
      ADC0SEQ3_IRQn = 17,
      WDT01_IRQn = 18,
      TIMER0A_IRQn = 19,
      TIMER0B_IRQn = 20,
      TIMER1A_IRQn = 21,
      TIMER1B_IRQn = 22,
      TIMER2A_IRQn = 23,
      TIMER2B_IRQn = 24,
      ACMP0_IRQn = 25,
      ACMP1_IRQn = 26,
      ACMP2_IRQn = 27,
      SYSCTL_IRQn = 28,
      FLASH_IRQn = 29,
      GPIOF_IRQn = 30,
      GPIOG_IRQn = 31,
      GPIOH_IRQn = 32,
      UART2_IRQn = 33,
      SSI1_IRQn = 34,
      TIMER3A_IRQn = 35,
      TIMER3B_IRQn = 36,
      I2C1_IRQn = 37,
      CAN0_IRQn = 38,
      CAN1_IRQn = 39,
      ETH_IRQn = 40,
      HIB_IRQn = 41,
      USB_IRQn = 42,
      PWM0GEN3_IRQn = 43,
      UDMASOFT_IRQn = 44,
      UDMAERROR_IRQn = 45,
      ADC1SEQ0_IRQn = 46,
      ADC1SEQ1_IRQn = 47,
      ADC1SEQ2_IRQn = 48,
      ADC1SEQ3_IRQn = 49,
      EPI0_IRQn = 50,
      GPIOJ_IRQn = 51,
      GPIOK_IRQn = 52,
      GPIOL_IRQn = 53,
      SSI2_IRQn = 54,
      SSI3_IRQn = 55,
      UART3_IRQn = 56,
      UART4_IRQn = 57,
      UART5_IRQn = 58,
      UART6_IRQn = 59,
      UART7_IRQn = 60,
      I2C2_IRQn = 61,
      I2C3_IRQn = 62,
      TIMER4A_IRQn = 63,
      TIMER4B_IRQn = 64,
      TIMER5A_IRQn = 65,
      TIMER5B_IRQn = 66,
      SYSEXC_IRQn = 67,
      RES84_IRQn = 68,
      RES85_IRQn = 69,
      I2C4_IRQn = 70,
      I2C5_IRQn = 71,
      GPIOM_IRQn = 72,
      GPION_IRQn = 73,
      RES90_IRQn = 74,
      TAMPER_IRQn = 75,
      GPIOP_IRQn = 76,
      GPIOP1_IRQn = 77,
      GPIOP2_IRQn = 78,
      GPIOP3_IRQn = 79,
      GPIOP4_IRQn = 80,
      GPIOP5_IRQn = 81,
      GPIOP6_IRQn = 82,
      GPIOP7_IRQn = 83,
      GPIOQ_IRQn = 84,
      GPIOQ1_IRQn = 85,
      GPIOQ2_IRQn = 86,
      GPIOQ3_IRQn = 87,
      GPIOQ4_IRQn = 88,
      GPIOQ5_IRQn = 89,
      GPIOQ6_IRQn = 90,
      GPIOQ7_IRQn = 91,
      GPIOR_IRQn = 92,
      GPIOS_IRQn = 93,
      SHA_MD5_IRQn = 94,
      AES_IRQn = 95,
      DES_IRQn = 96,
      LCD_IRQn = 97,
      TIMER6A_IRQn = 98,
      TIMER6B_IRQn = 99,
      TIMER7A_IRQn = 100,
      TIMER7B_IRQn = 101,
      I2C6_IRQn = 102,
      I2C7_IRQn = 103,
      KEYBOARD_IRQn = 104,
      ONEWIRE_IRQn = 105,
      PS2_IRQn = 106,
      LEDSEQ_IRQn = 107,
      IR_IRQn = 108,
      I2C8_IRQn = 109,
      I2C9_IRQn = 110,
      GPIOT_IRQn = 111,
      FAN_IRQn = 112,
      RES129_IRQn = 113,
}IRQn_Type;


typedef enum
{
    NVIC_enVECTOR_PRI_SSI2 = 0UL,
    NVIC_enVECTOR_PRI_GPIOC = 5UL,
    NVIC_enVECTOR_PRI_GPIOD = 5UL,
    NVIC_enVECTOR_PRI_ADC0SEQ0 = 5UL,
    NVIC_enVECTOR_PRI_ADC0SEQ1 = 5UL,
    NVIC_enVECTOR_PRI_ADC0SEQ2 = 5UL,
    NVIC_enVECTOR_PRI_TIMER0A = 6UL,
    NVIC_enVECTOR_PRI_GPIOL = 6UL,
    NVIC_enVECTOR_PRI_PWM0GEN2 = 7UL,

     NVIC_enVECTOR_PRI_GPIOA = 7UL,
     NVIC_enVECTOR_PRI_GPIOB = 7UL,
     NVIC_enVECTOR_PRI_GPIOE = 7UL,
     NVIC_enVECTOR_PRI_UART0 = 7UL,
     NVIC_enVECTOR_PRI_UART1 = 7UL,
     NVIC_enVECTOR_PRI_SSI0 = 7UL,
     NVIC_enVECTOR_PRI_I2C0 = 7UL,
     NVIC_enVECTOR_PRI_PWM0FAULT = 7UL,
     NVIC_enVECTOR_PRI_PWM0GEN0 = 7UL,
     NVIC_enVECTOR_PRI_PWM0GEN1 = 7UL,
     NVIC_enVECTOR_PRI_QEI0 = 7UL,
     NVIC_enVECTOR_PRI_ADC0SEQ3 = 7UL,
     NVIC_enVECTOR_PRI_WDT01 = 7UL,
     NVIC_enVECTOR_PRI_TIMER0B = 7UL,
     NVIC_enVECTOR_PRI_TIMER1A = 7UL,
     NVIC_enVECTOR_PRI_TIMER1B = 7UL,
     NVIC_enVECTOR_PRI_TIMER2A = 7UL,
     NVIC_enVECTOR_PRI_TIMER2B = 7UL,
     NVIC_enVECTOR_PRI_ACMP0 = 7UL,
     NVIC_enVECTOR_PRI_ACMP1 = 7UL,
     NVIC_enVECTOR_PRI_ACMP2 = 7UL,
     NVIC_enVECTOR_PRI_SYSCTL = 7UL,
     NVIC_enVECTOR_PRI_FLASH = 7UL,
     NVIC_enVECTOR_PRI_GPIOF = 7UL,
     NVIC_enVECTOR_PRI_GPIOG = 7UL,
     NVIC_enVECTOR_PRI_GPIOH = 7UL,
     NVIC_enVECTOR_PRI_UART2 = 7UL,
     NVIC_enVECTOR_PRI_SSI1 = 7UL,
     NVIC_enVECTOR_PRI_TIMER3A = 7UL,
     NVIC_enVECTOR_PRI_TIMER3B = 7UL,
     NVIC_enVECTOR_PRI_I2C1 = 7UL,
     NVIC_enVECTOR_PRI_CAN0 = 7UL,
     NVIC_enVECTOR_PRI_CAN1 = 7UL,
     NVIC_enVECTOR_PRI_ETH = 7UL,
     NVIC_enVECTOR_PRI_HIB = 7UL,
     NVIC_enVECTOR_PRI_USB = 7UL,
     NVIC_enVECTOR_PRI_PWM0GEN3 = 7UL,
     NVIC_enVECTOR_PRI_UDMASOFT = 7UL,
     NVIC_enVECTOR_PRI_UDMAERROR = 7UL,
     NVIC_enVECTOR_PRI_ADC1SEQ0 = 7UL,
     NVIC_enVECTOR_PRI_ADC1SEQ1 = 7UL,
     NVIC_enVECTOR_PRI_ADC1SEQ2 = 7UL,
     NVIC_enVECTOR_PRI_ADC1SEQ3 = 7UL,
     NVIC_enVECTOR_PRI_EPI0 = 7UL,
     NVIC_enVECTOR_PRI_GPIOJ = 7UL,
     NVIC_enVECTOR_PRI_GPIOK = 7UL,
     NVIC_enVECTOR_PRI_SSI3 = 7UL,
     NVIC_enVECTOR_PRI_UART3 = 7UL,
     NVIC_enVECTOR_PRI_UART4 = 7UL,
     NVIC_enVECTOR_PRI_UART5 = 7UL,
     NVIC_enVECTOR_PRI_UART6 = 7UL,
     NVIC_enVECTOR_PRI_UART7 = 7UL,
     NVIC_enVECTOR_PRI_I2C2 = 7UL,
     NVIC_enVECTOR_PRI_I2C3 = 7UL,
     NVIC_enVECTOR_PRI_TIMER4A = 7UL,
     NVIC_enVECTOR_PRI_TIMER4B = 7UL,
     NVIC_enVECTOR_PRI_TIMER5A = 7UL,
     NVIC_enVECTOR_PRI_TIMER5B = 7UL,
     NVIC_enVECTOR_PRI_SYSEXC = 7UL,
     NVIC_enVECTOR_PRI_RES84 = 7UL,
     NVIC_enVECTOR_PRI_RES85 = 7UL,
     NVIC_enVECTOR_PRI_I2C4 = 7UL,
     NVIC_enVECTOR_PRI_I2C5 = 7UL,
     NVIC_enVECTOR_PRI_GPIOM = 7UL,
     NVIC_enVECTOR_PRI_GPION = 7UL,
     NVIC_enVECTOR_PRI_RES90 = 7UL,
     NVIC_enVECTOR_PRI_TAMPER = 7UL,
     NVIC_enVECTOR_PRI_GPIOP = 7UL,
     NVIC_enVECTOR_PRI_GPIOP1 = 7UL,
     NVIC_enVECTOR_PRI_GPIOP2 = 7UL,
     NVIC_enVECTOR_PRI_GPIOP3 = 7UL,
     NVIC_enVECTOR_PRI_GPIOP4 = 7UL,
     NVIC_enVECTOR_PRI_GPIOP5 = 7UL,
     NVIC_enVECTOR_PRI_GPIOP6 = 7UL,
     NVIC_enVECTOR_PRI_GPIOP7 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ1 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ2 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ3 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ4 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ5 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ6 = 7UL,
     NVIC_enVECTOR_PRI_GPIOQ7 = 7UL,
     NVIC_enVECTOR_PRI_GPIOR = 7UL,
     NVIC_enVECTOR_PRI_GPIOS = 7UL,
     NVIC_enVECTOR_PRI_SHA_MD5 = 7UL,
     NVIC_enVECTOR_PRI_AES = 7UL,
     NVIC_enVECTOR_PRI_DES = 7UL,
     NVIC_enVECTOR_PRI_LCD = 7UL,
     NVIC_enVECTOR_PRI_TIMER6A = 7UL,
     NVIC_enVECTOR_PRI_TIMER6B = 7UL,
     NVIC_enVECTOR_PRI_TIMER7A = 7UL,
     NVIC_enVECTOR_PRI_TIMER7B = 7UL,
     NVIC_enVECTOR_PRI_I2C6 = 7UL,
     NVIC_enVECTOR_PRI_I2C7 = 7UL,
     NVIC_enVECTOR_PRI_KEYBOARD = 7UL,
     NVIC_enVECTOR_PRI_ONEWIRE = 7UL,
     NVIC_enVECTOR_PRI_PS2 = 7UL,
     NVIC_enVECTOR_PRI_LEDSEQ = 7UL,
     NVIC_enVECTOR_PRI_IR = 7UL,
     NVIC_enVECTOR_PRI_I2C8 = 7UL,
     NVIC_enVECTOR_PRI_I2C9 = 7UL,
     NVIC_enVECTOR_PRI_GPIOT = 7UL,
     NVIC_enVECTOR_PRI_FAN = 7UL,
     NVIC_enVECTOR_PRI_RES129 = 7UL,
}NVIC_nVECTOR_PRI;


typedef MCU_Register_t NVIC_Register_t;
typedef MCU_pvfIRQSourceHandler_t NVIC_pvfIRQSourceHandler_t;

typedef enum
{
    NVIC_enPriority_SSI2 = 0UL,
    NVIC_enPriority_GPIOC = 5UL,
    NVIC_enPriority_GPIOD = 5UL,
    NVIC_enPriority_ADC0SEQ0 = 5UL,
    NVIC_enPriority_ADC0SEQ1 = 5UL,
    NVIC_enPriority_ADC0SEQ2 = 5UL,
    NVIC_enPriority_TIMER0A = 6UL,
    NVIC_enPriority_GPIOL = 6UL,
    NVIC_enPriority_PWM0GEN2 = 7UL,

     NVIC_enPriority_GPIOA = 7UL,
     NVIC_enPriority_GPIOB = 7UL,
     NVIC_enPriority_GPIOE = 7UL,
     NVIC_enPriority_UART0 = 7UL,
     NVIC_enPriority_UART1 = 7UL,
     NVIC_enPriority_SSI0 = 7UL,
     NVIC_enPriority_I2C0 = 7UL,
     NVIC_enPriority_PWM0FAULT = 7UL,
     NVIC_enPriority_PWM0GEN0 = 7UL,
     NVIC_enPriority_PWM0GEN1 = 7UL,
     NVIC_enPriority_QEI0 = 7UL,
     NVIC_enPriority_ADC0SEQ3 = 7UL,
     NVIC_enPriority_WDT01 = 7UL,
     NVIC_enPriority_TIMER0B = 7UL,
     NVIC_enPriority_TIMER1A = 7UL,
     NVIC_enPriority_TIMER1B = 7UL,
     NVIC_enPriority_TIMER2A = 7UL,
     NVIC_enPriority_TIMER2B = 7UL,
     NVIC_enPriority_ACMP0 = 7UL,
     NVIC_enPriority_ACMP1 = 7UL,
     NVIC_enPriority_ACMP2 = 7UL,
     NVIC_enPriority_SYSCTL = 7UL,
     NVIC_enPriority_FLASH = 7UL,
     NVIC_enPriority_GPIOF = 7UL,
     NVIC_enPriority_GPIOG = 7UL,
     NVIC_enPriority_GPIOH = 7UL,
     NVIC_enPriority_UART2 = 7UL,
     NVIC_enPriority_SSI1 = 7UL,
     NVIC_enPriority_TIMER3A = 7UL,
     NVIC_enPriority_TIMER3B = 7UL,
     NVIC_enPriority_I2C1 = 7UL,
     NVIC_enPriority_CAN0 = 7UL,
     NVIC_enPriority_CAN1 = 7UL,
     NVIC_enPriority_ETH = 7UL,
     NVIC_enPriority_HIB = 7UL,
     NVIC_enPriority_USB = 7UL,
     NVIC_enPriority_PWM0GEN3 = 7UL,
     NVIC_enPriority_UDMASOFT = 7UL,
     NVIC_enPriority_UDMAERROR = 7UL,
     NVIC_enPriority_ADC1SEQ0 = 7UL,
     NVIC_enPriority_ADC1SEQ1 = 7UL,
     NVIC_enPriority_ADC1SEQ2 = 7UL,
     NVIC_enPriority_ADC1SEQ3 = 7UL,
     NVIC_enPriority_EPI0 = 7UL,
     NVIC_enPriority_GPIOJ = 7UL,
     NVIC_enPriority_GPIOK = 7UL,
     NVIC_enPriority_SSI3 = 7UL,
     NVIC_enPriority_UART3 = 7UL,
     NVIC_enPriority_UART4 = 7UL,
     NVIC_enPriority_UART5 = 7UL,
     NVIC_enPriority_UART6 = 7UL,
     NVIC_enPriority_UART7 = 7UL,
     NVIC_enPriority_I2C2 = 7UL,
     NVIC_enPriority_I2C3 = 7UL,
     NVIC_enPriority_TIMER4A = 7UL,
     NVIC_enPriority_TIMER4B = 7UL,
     NVIC_enPriority_TIMER5A = 7UL,
     NVIC_enPriority_TIMER5B = 7UL,
     NVIC_enPriority_SYSEXC = 7UL,
     NVIC_enPriority_RES84 = 7UL,
     NVIC_enPriority_RES85 = 7UL,
     NVIC_enPriority_I2C4 = 7UL,
     NVIC_enPriority_I2C5 = 7UL,
     NVIC_enPriority_GPIOM = 7UL,
     NVIC_enPriority_GPION = 7UL,
     NVIC_enPriority_RES90 = 7UL,
     NVIC_enPriority_TAMPER = 7UL,
     NVIC_enPriority_GPIOP = 7UL,
     NVIC_enPriority_GPIOP1 = 7UL,
     NVIC_enPriority_GPIOP2 = 7UL,
     NVIC_enPriority_GPIOP3 = 7UL,
     NVIC_enPriority_GPIOP4 = 7UL,
     NVIC_enPriority_GPIOP5 = 7UL,
     NVIC_enPriority_GPIOP6 = 7UL,
     NVIC_enPriority_GPIOP7 = 7UL,
     NVIC_enPriority_GPIOQ = 7UL,
     NVIC_enPriority_GPIOQ1 = 7UL,
     NVIC_enPriority_GPIOQ2 = 7UL,
     NVIC_enPriority_GPIOQ3 = 7UL,
     NVIC_enPriority_GPIOQ4 = 7UL,
     NVIC_enPriority_GPIOQ5 = 7UL,
     NVIC_enPriority_GPIOQ6 = 7UL,
     NVIC_enPriority_GPIOQ7 = 7UL,
     NVIC_enPriority_GPIOR = 7UL,
     NVIC_enPriority_GPIOS = 7UL,
     NVIC_enPriority_SHA_MD5 = 7UL,
     NVIC_enPriority_AES = 7UL,
     NVIC_enPriority_DES = 7UL,
     NVIC_enPriority_LCD = 7UL,
     NVIC_enPriority_TIMER6A = 7UL,
     NVIC_enPriority_TIMER6B = 7UL,
     NVIC_enPriority_TIMER7A = 7UL,
     NVIC_enPriority_TIMER7B = 7UL,
     NVIC_enPriority_I2C6 = 7UL,
     NVIC_enPriority_I2C7 = 7UL,
     NVIC_enPriority_KEYBOARD = 7UL,
     NVIC_enPriority_ONEWIRE = 7UL,
     NVIC_enPriority_PS2 = 7UL,
     NVIC_enPriority_LEDSEQ = 7UL,
     NVIC_enPriority_IR = 7UL,
     NVIC_enPriority_I2C8 = 7UL,
     NVIC_enPriority_I2C9 = 7UL,
     NVIC_enPriority_GPIOT = 7UL,
     NVIC_enPriority_FAN = 7UL,
     NVIC_enPriority_RES129 = 7UL,
}NVIC_nPriority;

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_ENUM_H_ */
