/*
 * SYSCTL_RegisterDefines_DSCLKCFG.h
 *
 *  Created on: 13 jun. 2021
 *      Author: InDeviceMex
 */

#ifndef XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_DSCLKCFG_H_
#define XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_DSCLKCFG_H_

#include <xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h>

/******************************************************************************************
************************************ 14 DSCLKCFG *********************************************
******************************************************************************************/
/*--------*/
#define SYSCTL_DSCLKCFG_R_DSSYSDIV_MASK    ((UBase_t) 0x000003FFUL)
#define SYSCTL_DSCLKCFG_R_DSSYSDIV_BIT    (0UL)

#define SYSCTL_DSCLKCFG_DSSYSDIV_MASK    ((UBase_t) 0x000003FFUL)
/*--------*/

/*--------*/
#define SYSCTL_DSCLKCFG_R_DSOSCSRC_MASK    ((UBase_t) 0x00F00000UL)
#define SYSCTL_DSCLKCFG_R_DSOSCSRC_BIT    (20UL)
#define SYSCTL_DSCLKCFG_R_DSOSCSRC_PIOSC    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSCLKCFG_R_DSOSCSRC_LFIOSC    ((UBase_t) 0x00200000UL)
#define SYSCTL_DSCLKCFG_R_DSOSCSRC_MOSC    ((UBase_t) 0x00300000UL)
#define SYSCTL_DSCLKCFG_R_DSOSCSRC_RTCOSC    ((UBase_t) 0x00400000UL)

#define SYSCTL_DSCLKCFG_DSOSCSRC_MASK    ((UBase_t) 0x0000000FUL)
#define SYSCTL_DSCLKCFG_DSOSCSRC_PIOSC    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSCLKCFG_DSOSCSRC_LFIOSC    ((UBase_t) 0x00000002UL)
#define SYSCTL_DSCLKCFG_DSOSCSRC_MOSC    ((UBase_t) 0x00000003UL)
#define SYSCTL_DSCLKCFG_DSOSCSRC_RTCOSC    ((UBase_t) 0x00000004UL)
/*--------*/

/*--------*/
#define SYSCTL_DSCLKCFG_R_MOSCDPD_MASK    ((UBase_t) 0x40000000UL)
#define SYSCTL_DSCLKCFG_R_MOSCDPD_BIT    (30UL)
#define SYSCTL_DSCLKCFG_R_MOSCDPD_DIS    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSCLKCFG_R_MOSCDPD_ENA    ((UBase_t) 0x40000000UL)

#define SYSCTL_DSCLKCFG_MOSCDPD_MASK    ((UBase_t) 0x00000001UL)
#define SYSCTL_DSCLKCFG_MOSCDPD_DIS    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSCLKCFG_MOSCDPD_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define SYSCTL_DSCLKCFG_R_PIOSCPD_MASK    ((UBase_t) 0x80000000UL)
#define SYSCTL_DSCLKCFG_R_PIOSCPD_BIT    (31UL)
#define SYSCTL_DSCLKCFG_R_PIOSCPD_ENA    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSCLKCFG_R_PIOSCPD_DIS    ((UBase_t) 0x80000000UL)

#define SYSCTL_DSCLKCFG_PIOSCPD_MASK    ((UBase_t) 0x00000001UL)
#define SYSCTL_DSCLKCFG_PIOSCPD_ENA    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSCLKCFG_PIOSCPD_DIS    ((UBase_t) 0x00000001UL)
/*--------*/




#endif /* XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_DSCLKCFG_H_ */
