/*
 * SYSCTL_RegisterDefines_RESBEHAVCTL.h
 *
 *  Created on: 13 jun. 2021
 *      Author: InDeviceMex
 */

#ifndef XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_RESBEHAVCTL_H_
#define XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_RESBEHAVCTL_H_

#include <xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h>

/******************************************************************************************
************************************ 30 RESBEHAVCTL *********************************************
******************************************************************************************/
/*--------*/
#define SYSCTL_RESBEHAVCTL_R_EXTRES_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_RESBEHAVCTL_R_EXTRES_BIT    (0UL)
#define SYSCTL_RESBEHAVCTL_R_EXTRES_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_R_EXTRES_SYSRESET    ((UBase_t) 0x00000002UL)
#define SYSCTL_RESBEHAVCTL_R_EXTRES_POR    ((UBase_t) 0x00000003UL)

#define SYSCTL_RESBEHAVCTL_EXTRES_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_RESBEHAVCTL_EXTRES_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_EXTRES_SYSRESET    ((UBase_t) 0x00000002UL)
#define SYSCTL_RESBEHAVCTL_EXTRES_POR    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define SYSCTL_RESBEHAVCTL_R_BOR_MASK    ((UBase_t) 0x0000000CUL)
#define SYSCTL_RESBEHAVCTL_R_BOR_BIT    (2UL)
#define SYSCTL_RESBEHAVCTL_R_BOR_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_R_BOR_SYSRESET    ((UBase_t) 0x00000008UL)
#define SYSCTL_RESBEHAVCTL_R_BOR_POR    ((UBase_t) 0x0000000CUL)

#define SYSCTL_RESBEHAVCTL_BOR_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_RESBEHAVCTL_BOR_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_BOR_SYSRESET    ((UBase_t) 0x00000002UL)
#define SYSCTL_RESBEHAVCTL_BOR_POR    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define SYSCTL_RESBEHAVCTL_R_WDOG0_MASK    ((UBase_t) 0x00000030UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG0_BIT    (4UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG0_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG0_SYSRESET    ((UBase_t) 0x00000020UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG0_POR    ((UBase_t) 0x00000030UL)

#define SYSCTL_RESBEHAVCTL_WDOG0_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_RESBEHAVCTL_WDOG0_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_WDOG0_SYSRESET    ((UBase_t) 0x00000002UL)
#define SYSCTL_RESBEHAVCTL_WDOG0_POR    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define SYSCTL_RESBEHAVCTL_R_WDOG1_MASK    ((UBase_t) 0x000000C0UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG1_BIT    (6UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG1_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG1_SYSRESET    ((UBase_t) 0x00000080UL)
#define SYSCTL_RESBEHAVCTL_R_WDOG1_POR    ((UBase_t) 0x000000C0UL)

#define SYSCTL_RESBEHAVCTL_WDOG1_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_RESBEHAVCTL_WDOG1_DEFAULT    ((UBase_t) 0x00000000UL)
#define SYSCTL_RESBEHAVCTL_WDOG1_SYSRESET    ((UBase_t) 0x00000002UL)
#define SYSCTL_RESBEHAVCTL_WDOG1_POR    ((UBase_t) 0x00000003UL)
/*--------*/

#endif /* XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_RESBEHAVCTL_H_ */
