/*
 * SYSCTL_RegisterDefines_DSLPPWRCFG.h
 *
 *  Created on: 13 jun. 2021
 *      Author: InDeviceMex
 */

#ifndef XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_DSLPPWRCFG_H_
#define XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_DSLPPWRCFG_H_

#include <xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h>

/******************************************************************************************
************************************23 DSLPPWRCFG *********************************************
******************************************************************************************/
/*--------*/
#define SYSCTL_DSLPPWRCFG_R_SRAMPM_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_DSLPPWRCFG_R_SRAMPM_BIT    (0UL)
#define SYSCTL_DSLPPWRCFG_R_SRAMPM_ACTIVE    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_R_SRAMPM_STANDBY    ((UBase_t) 0x00000001UL)
#define SYSCTL_DSLPPWRCFG_R_SRAMPM_LOWPOWER    ((UBase_t) 0x00000003UL)

#define SYSCTL_DSLPPWRCFG_SRAMPM_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_DSLPPWRCFG_SRAMPM_ACTIVE    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_SRAMPM_STANDBY    ((UBase_t) 0x00000001UL)
#define SYSCTL_DSLPPWRCFG_SRAMPM_LOWPOWER    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define SYSCTL_DSLPPWRCFG_R_FLASHPM_MASK    ((UBase_t) 0x00000030UL)
#define SYSCTL_DSLPPWRCFG_R_FLASHPM_BIT    (2UL)
#define SYSCTL_DSLPPWRCFG_R_FLASHPM_ACTIVE    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_R_FLASHPM_LOWPOWER    ((UBase_t) 0x00000020UL)

#define SYSCTL_DSLPPWRCFG_FLASHPM_MASK    ((UBase_t) 0x00000003UL)
#define SYSCTL_DSLPPWRCFG_FLASHPM_ACTIVE    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_FLASHPM_LOWPOWER    ((UBase_t) 0x00000002UL)
/*--------*/

/*--------*/
#define SYSCTL_DSLPPWRCFG_R_TSPD_MASK    ((UBase_t) 0x00000100UL)
#define SYSCTL_DSLPPWRCFG_R_TSPD_BIT    (8UL)
#define SYSCTL_DSLPPWRCFG_R_TSPD_DIS    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_R_TSPD_ENA    ((UBase_t) 0x00000100UL)

#define SYSCTL_DSLPPWRCFG_TSPD_MASK    ((UBase_t) 0x00000001UL)
#define SYSCTL_DSLPPWRCFG_TSPD_DIS    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_TSPD_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define SYSCTL_DSLPPWRCFG_R_LDOSM_MASK    ((UBase_t) 0x00000200UL)
#define SYSCTL_DSLPPWRCFG_R_LDOSM_BIT    (9UL)
#define SYSCTL_DSLPPWRCFG_R_LDOSM_DIS    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_R_LDOSM_ENA    ((UBase_t) 0x00000200UL)

#define SYSCTL_DSLPPWRCFG_LDOSM_MASK    ((UBase_t) 0x00000001UL)
#define SYSCTL_DSLPPWRCFG_LDOSM_DIS    ((UBase_t) 0x00000000UL)
#define SYSCTL_DSLPPWRCFG_LDOSM_ENA    ((UBase_t) 0x00000001UL)
/*--------*/


#endif /* XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_DSLPPWRCFG_H_ */
