/**
 *
 * @file PWM_RegisterDefines_GEN_FAULT_SRC1.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 24 dic. 2021 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 24 dic. 2021     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_FAULT_SRC1_H_
#define XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_FAULT_SRC1_H_

#include <xDriver_MCU/PWM/Peripheral/xHeader/PWM_Enum.h>

/******************************************************************************************
************************************ 26 GEN_FAULT_SRC1 *********************************************
******************************************************************************************/
/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP0_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP0_BIT    ((UBase_t) 0UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP0_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP0_ENA    ((UBase_t) 0x00000001UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP0_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP0_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP0_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP1_MASK    ((UBase_t) 0x00000002UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP1_BIT    ((UBase_t) 1UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP1_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP1_ENA    ((UBase_t) 0x00000002UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP1_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP1_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP1_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP2_MASK    ((UBase_t) 0x00000004UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP2_BIT    ((UBase_t) 2UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP2_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP2_ENA    ((UBase_t) 0x00000004UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP2_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP2_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP2_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP3_MASK    ((UBase_t) 0x00000008UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP3_BIT    ((UBase_t) 3UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP3_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP3_ENA    ((UBase_t) 0x00000008UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP3_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP3_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP3_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP4_MASK    ((UBase_t) 0x00000010UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP4_BIT    ((UBase_t) 4UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP4_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP4_ENA    ((UBase_t) 0x00000010UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP4_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP4_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP4_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP5_MASK    ((UBase_t) 0x00000020UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP5_BIT    ((UBase_t) 5UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP5_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP5_ENA    ((UBase_t) 0x00000020UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP5_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP5_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP5_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP6_MASK    ((UBase_t) 0x00000040UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP6_BIT    ((UBase_t) 6UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP6_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP6_ENA    ((UBase_t) 0x00000040UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP6_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP6_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP6_ENA    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP7_MASK    ((UBase_t) 0x00000080UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP7_BIT    ((UBase_t) 7UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP7_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_R_DCMP7_ENA    ((UBase_t) 0x00000080UL)

#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP7_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP7_DIS    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_ENABLE_DCMP7_ENA    ((UBase_t) 0x00000001UL)
/*--------*/


#endif /* XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_FAULT_SRC1_H_ */
