/**
 *
 * @file PWM_RegisterDefines_GEN_EXT_FLTSTAT1.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 24 dic. 2021 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 24 dic. 2021     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_EXT_FLTSTAT1_H_
#define XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_EXT_FLTSTAT1_H_

#include <xDriver_MCU/PWM/Peripheral/xHeader/PWM_Enum.h>

/******************************************************************************************
************************************ 30 GEN_EXT_FLTSTAT1 *********************************************
******************************************************************************************/
/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP0_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP0_BIT    ((UBase_t) 0UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP0_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP0_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP0_CLEAR    ((UBase_t) 0x00000001UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP0_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP0_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP0_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP0_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP1_MASK    ((UBase_t) 0x00000002UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP1_BIT    ((UBase_t) 1UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP1_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP1_ACTIVE    ((UBase_t) 0x00000002UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP1_CLEAR    ((UBase_t) 0x00000002UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP1_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP1_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP1_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP1_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP2_MASK    ((UBase_t) 0x00000004UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP2_BIT    ((UBase_t) 2UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP2_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP2_ACTIVE    ((UBase_t) 0x00000004UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP2_CLEAR    ((UBase_t) 0x00000004UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP2_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP2_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP2_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP2_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP3_MASK    ((UBase_t) 0x00000008UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP3_BIT    ((UBase_t) 3UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP3_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP3_ACTIVE    ((UBase_t) 0x00000008UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP3_CLEAR    ((UBase_t) 0x00000008UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP3_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP3_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP3_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP3_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP4_MASK    ((UBase_t) 0x00000010UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP4_BIT    ((UBase_t) 4UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP4_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP4_ACTIVE    ((UBase_t) 0x00000010UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP4_CLEAR    ((UBase_t) 0x00000010UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP4_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP4_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP4_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP4_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP5_MASK    ((UBase_t) 0x00000020UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP5_BIT    ((UBase_t) 5UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP5_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP5_ACTIVE    ((UBase_t) 0x00000020UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP5_CLEAR    ((UBase_t) 0x00000020UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP5_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP5_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP5_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP5_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP6_MASK    ((UBase_t) 0x00000040UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP6_BIT    ((UBase_t) 6UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP6_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP6_ACTIVE    ((UBase_t) 0x00000040UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP6_CLEAR    ((UBase_t) 0x00000040UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP6_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP6_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP6_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP6_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

/*--------*/
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP7_MASK    ((UBase_t) 0x00000080UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP7_BIT    ((UBase_t) 7UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP7_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP7_ACTIVE    ((UBase_t) 0x00000080UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_R_DCMP7_CLEAR    ((UBase_t) 0x00000080UL)

#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP7_MASK    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP7_NOACTIVE    ((UBase_t) 0x00000000UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP7_ACTIVE    ((UBase_t) 0x00000001UL)
#define PWM_GEN_EXT_FAULT_DCMP_STAT_DCMP7_CLEAR    ((UBase_t) 0x00000001UL)
/*--------*/

#endif /* XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_EXT_FLTSTAT1_H_ */
