/**
 *
 * @file PWM_RegisterDefines_GEN_GENA.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 24 dic. 2021 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 24 dic. 2021     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_GENA_H_
#define XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_GENA_H_

#include <xDriver_MCU/PWM/Peripheral/xHeader/PWM_Enum.h>

/******************************************************************************************
************************************ 20 GEN_GENA *********************************************
******************************************************************************************/
/*--------*/
#define PWM_GEN_OUTA_ACTION_R_ZERO_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_R_ZERO_BIT    ((UBase_t) 0UL)
#define PWM_GEN_OUTA_ACTION_R_ZERO_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_R_ZERO_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_R_ZERO_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_R_ZERO_HIGH    ((UBase_t) 0x00000003UL)

#define PWM_GEN_OUTA_ACTION_ZERO_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_ZERO_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_ZERO_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_ZERO_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_ZERO_HIGH    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define PWM_GEN_OUTA_ACTION_R_LOAD_MASK    ((UBase_t) 0x0000000CUL)
#define PWM_GEN_OUTA_ACTION_R_LOAD_BIT    ((UBase_t) 2UL)
#define PWM_GEN_OUTA_ACTION_R_LOAD_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_R_LOAD_INVERT   ((UBase_t) 0x00000004UL)
#define PWM_GEN_OUTA_ACTION_R_LOAD_LOW    ((UBase_t) 0x00000008UL)
#define PWM_GEN_OUTA_ACTION_R_LOAD_HIGH    ((UBase_t) 0x0000000CUL)

#define PWM_GEN_OUTA_ACTION_LOAD_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_LOAD_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_LOAD_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_LOAD_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_LOAD_HIGH    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_UP_MASK    ((UBase_t) 0x00000030UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_UP_BIT    ((UBase_t) 4UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_UP_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_UP_INVERT   ((UBase_t) 0x00000010UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_UP_LOW    ((UBase_t) 0x00000020UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_UP_HIGH    ((UBase_t) 0x00000030UL)

#define PWM_GEN_OUTA_ACTION_OUTA_CMP_UP_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_UP_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_UP_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_UP_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_UP_HIGH    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_DOWN_MASK    ((UBase_t) 0x000000C0UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_DOWN_BIT    ((UBase_t) 6UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_DOWN_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_DOWN_INVERT   ((UBase_t) 0x00000040UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_DOWN_LOW    ((UBase_t) 0x00000080UL)
#define PWM_GEN_OUTA_ACTION_R_OUTA_CMP_DOWN_HIGH    ((UBase_t) 0x000000C0UL)

#define PWM_GEN_OUTA_ACTION_OUTA_CMP_DOWN_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_DOWN_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_DOWN_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_DOWN_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_OUTA_CMP_DOWN_HIGH    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_UP_MASK    ((UBase_t) 0x00000300UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_UP_BIT    ((UBase_t) 8UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_UP_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_UP_INVERT   ((UBase_t) 0x00000100UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_UP_LOW    ((UBase_t) 0x00000200UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_UP_HIGH    ((UBase_t) 0x00000300UL)

#define PWM_GEN_OUTA_ACTION_OUTB_CMP_UP_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_UP_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_UP_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_UP_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_UP_HIGH    ((UBase_t) 0x00000003UL)
/*--------*/

/*--------*/
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_DOWN_MASK    ((UBase_t) 0x00000C00UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_DOWN_BIT    ((UBase_t) 10UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_DOWN_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_DOWN_INVERT   ((UBase_t) 0x00000400UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_DOWN_LOW    ((UBase_t) 0x00000800UL)
#define PWM_GEN_OUTA_ACTION_R_OUTB_CMP_DOWN_HIGH    ((UBase_t) 0x00000C00UL)

#define PWM_GEN_OUTA_ACTION_OUTB_CMP_DOWN_MASK    ((UBase_t) 0x00000003UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_DOWN_NOTHING    ((UBase_t) 0x00000000UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_DOWN_INVERT   ((UBase_t) 0x00000001UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_DOWN_LOW    ((UBase_t) 0x00000002UL)
#define PWM_GEN_OUTA_ACTION_OUTB_CMP_DOWN_HIGH    ((UBase_t) 0x00000003UL)
/*--------*/

#endif /* XDRIVER_MCU_PWM_PERIPHERAL_REGISTER_REGISTERDEFINES_XHEADER_PWM_REGISTERDEFINES_GEN_GENA_H_ */
